/*
 * fatmap sandbox - SDL3 1280x720 framebuffer.
 *
 * Keys:
 *   1..9, 0, -, =  scene (gallery, blend modes, stress, texture, lines, aa vs aliased, 3d, troll,
 *            animated characters, helmet, shaders, seascape)
 *   S        cycle SIMD level (scalar / sse2 / avx2 / neon)
 *   A        toggle anti-aliasing (analytic / aliased)
 *   B        toggle bilinear filtering (image smoothing)
 *   T        toggle multithreaded command lists (deferred rendering)
 *   F        3d: cycle texture filter (nearest / bilinear / trilinear)
 *   M        3d: toggle perspective correct texturing (affine = PS1 look)
 *   N        3d: cycle MSAA (off / 4x / 8x)
 *   C        characters: cycle the fox animation clip
 *   G        shaders: cycle C shader programs / SPIR-V interpreted / SPIR-V compiled
 *            to C (build time) / fixed function T&L; seascape: interpreted / compiled
 *   Up/Down  seascape: render scale (1/1 .. 1/8, upscaled to the window)
 *   X        seascape: fast shader math (fm_fast_*, GPU precision) / 1 ulp math
 *
 * Frames are always rendered into the swapchain back buffer, then presented;
 * the presented front buffer is what gets uploaded to SDL.
 *   Up/Down  stress: double / halve object count
 *   P        print profiler report to the console
 *   V        toggle vsync
 *   Space    pause animation, Esc quit
 *
 * fatmap_sandbox --shots <dir>   renders every scene for 60 frames, prints the
 *                                average draw time, saves <dir>/scene_N.png, exits
 *                --scene N       (with --shots) only scene N (1 = gallery)
 */
#include <SDL3/SDL.h>
#include <SDL3/SDL_main.h>
#include <fatmap/fatmap.h>
#include "obj_loader.h"
#include "gltf_loader.h"
#include "image_load.h"
#if FM_FEATURE_SPIRV
#  include "spirv_shaders.h" /* from sandbox/shaders (tools/compile_shaders.py) */
#endif
#include <math.h>
#include <stdio.h>
#ifndef FM_SANDBOX_AOT
#  define FM_SANDBOX_AOT 0
#endif
#include <stdlib.h>
#include <string.h>

#define W 1280
#define H 720
#define TAU 6.2831853f

/* shader pipelines (G): C callbacks, SPIR-V interpreted, SPIR-V compiled
 * to C at build time (fm3d_spirv_to_c), fixed function */
enum { SH_C = 0, SH_SPIRV, SH_JIT, SH_AOT, SH_FIXED, SH_COUNT };
#define SH_IS_SPIRV(m) ((m) == SH_SPIRV || (m) == SH_JIT || (m) == SH_AOT)
#if FM_SANDBOX_AOT
fm3d_program aot_helmet_program(void); /* sandbox_aot.c, generated by sandbox/spirv_aot_gen.c */
fm3d_program aot_flag_program(void);
fm3d_program aot_seascape_program(void);
fm3d_program aot_seascape_fast_program(void);
#endif

typedef struct app {
    fm_swapchain* sc;
    fm_surface*   fb; /* current back buffer */
    fm3d_ctx*     c3;
    fm3d_texture* floor_tex;
    fm3d_texture* crate_tex;
    int           filter3d;
    int           persp3d;
    int           msaa3d;
    int           fox_clip;
    int           shader_mode; /* shaders scenes: SH_* */
    int           sea_div;     /* seascape: render at W / sea_div x H / sea_div */
    int           sea_fast;    /* seascape: fm3d_spirv_set_fast_math */
    fm2d_ctx*   c;
    fm_surface* tex;
    fm_surface* sprite;
    fm_surface* tiles[FM_OP_COUNT];
    fm2d_ctx*   tile_ctx;
    fm_executor* exec;
    int         threaded;
    int         scene;
    int         aa;
    int         smooth;
    int         count;
    float       t;
    float       mx, my;
} app;

static uint32_t g_rng = 1;
static uint32_t rnd(void)
{
    g_rng ^= g_rng << 13;
    g_rng ^= g_rng >> 17;
    g_rng ^= g_rng << 5;
    return g_rng;
}
static float rndf(void) { return (float)(rnd() & 0xffffff) / 16777216.0f; }

static const char* g_scene_names[] = { "gallery", "blend modes", "stress", "texture", "lines", "aa vs aliased", "3d",
                                       "troll", "characters", "helmet", "shaders", "seascape" };
#define NSCENES 12

static fm_surface* make_texture(int w, int h)
{
    fm_surface* s = fm_surface_create(w, h, FM_FORMAT_ARGB32);
    for (int y = 0; y < h; y++) {
        uint32_t* r = fm_surface_row32(s, y);
        for (int x = 0; x < w; x++) {
            float fx = (float)x / w, fy = (float)y / h;
            int   chk = ((x / (w / 8)) + (y / (h / 8))) & 1;
            float d   = sqrtf((fx - 0.5f) * (fx - 0.5f) + (fy - 0.5f) * (fy - 0.5f));
            uint8_t rr = (uint8_t)(chk ? 230 : 40 + 150 * fx), gg = (uint8_t)(chk ? 200 : 60 + 150 * fy),
                    bb = (uint8_t)(chk ? 90 : 200);
            if (d < 0.2f) rr = gg = bb = 255;
            r[x] = fm_premultiply(FM_RGB(rr, gg, bb));
        }
    }
    return s;
}

static fm_surface* make_sprite(int n)
{
    fm_surface* s = fm_surface_create(n, n, FM_FORMAT_ARGB32);
    fm2d_ctx*   c = fm2d_create(s);
    fm2d_paint* g = fm2d_paint_radial(n * 0.4f, n * 0.4f, 1, n * 0.5f, n * 0.5f, n * 0.5f);
    fm2d_paint_add_stop(g, 0, FM_RGB(255, 255, 255));
    fm2d_paint_add_stop(g, 0.4f, FM_RGB(255, 170, 40));
    fm2d_paint_add_stop(g, 1, FM_RGBA(200, 40, 0, 0));
    fm2d_set_fill_paint(c, g);
    fm2d_fill_rect(c, 0, 0, (float)n, (float)n);
    fm2d_paint_release(g);
    fm2d_destroy(c);
    return s;
}

/* ---- scenes ----------------------------------------------------------------------- */

static void scene_gallery(app* a)
{
    fm2d_ctx* c = a->c;
    float     t = a->t;
    fm2d_clear(a->c, FM_RGB(22, 24, 30));

    fm2d_paint* lg = fm2d_paint_linear(0, 0, W, H);
    fm2d_paint_add_stop(lg, 0, FM_RGB(30, 40, 70));
    fm2d_paint_add_stop(lg, 1, FM_RGB(10, 10, 20));
    fm2d_set_fill_paint(c, lg);
    fm2d_fill_rect(c, 0, 0, W, H);
    fm2d_paint_release(lg);

    /* rotating star with radial gradient */
    fm2d_save(c);
    fm2d_translate(c, 220, 220);
    fm2d_rotate(c, t * 0.5f);
    fm2d_paint* rg = fm2d_paint_radial(0, 0, 10, 0, 0, 170);
    fm2d_paint_add_stop(rg, 0, FM_RGB(255, 250, 200));
    fm2d_paint_add_stop(rg, 0.6f, FM_RGB(255, 120, 40));
    fm2d_paint_add_stop(rg, 1, FM_RGBA(200, 0, 80, 180));
    fm2d_set_fill_paint(c, rg);
    fm2d_begin_path(c);
    for (int i = 0; i < 10; i++) {
        float r = (i & 1) ? 70.0f : 170.0f, ang = (float)i * TAU / 10.0f;
        if (i == 0)
            fm2d_move_to(c, cosf(ang) * r, sinf(ang) * r);
        else
            fm2d_line_to(c, cosf(ang) * r, sinf(ang) * r);
    }
    fm2d_close_path(c);
    fm2d_fill(c, FM_FILL_NONZERO);
    fm2d_set_line_width(c, 5);
    fm2d_set_line_join(c, FM2D_JOIN_ROUND);
    fm2d_set_stroke_color(c, FM_RGBA(255, 255, 255, 200));
    fm2d_stroke(c);
    fm2d_paint_release(rg);
    fm2d_restore(c);

    /* conic wheel */
    fm2d_paint* cg = fm2d_paint_conic(t, 560, 200);
    const fm_color hues[] = { FM_RGB(255, 0, 0), FM_RGB(255, 255, 0), FM_RGB(0, 255, 0), FM_RGB(0, 255, 255),
                              FM_RGB(0, 0, 255), FM_RGB(255, 0, 255), FM_RGB(255, 0, 0) };
    for (int i = 0; i < 7; i++) fm2d_paint_add_stop(cg, (float)i / 6.0f, hues[i]);
    fm2d_set_fill_paint(c, cg);
    fm2d_begin_path(c);
    fm2d_arc(c, 560, 200, 130, 0, TAU, 0);
    fm2d_arc(c, 560, 200, 60, 0, TAU, 1);
    fm2d_fill(c, FM_FILL_NONZERO);
    fm2d_paint_release(cg);

    /* joins and caps */
    const char* dummy = 0;
    (void)dummy;
    for (int i = 0; i < 3; i++) {
        fm2d_set_line_width(c, 18);
        fm2d_set_line_join(c, (fm2d_line_join)i);
        fm2d_set_line_cap(c, (fm2d_line_cap)i);
        fm2d_set_stroke_color(c, FM_RGBA(100, 200, 255, 230));
        fm2d_begin_path(c);
        float ox = 760 + (float)i * 170;
        fm2d_move_to(c, ox, 330);
        fm2d_line_to(c, ox + 60, 110 + sinf(t + (float)i) * 40);
        fm2d_line_to(c, ox + 120, 330);
        fm2d_stroke(c);
    }

    /* animated dashes around a round rect */
    float dash[4] = { 30, 10, 4, 10 };
    fm2d_set_line_dash(c, dash, 4);
    fm2d_set_line_dash_offset(c, -t * 40);
    fm2d_set_line_width(c, 5);
    fm2d_set_line_cap(c, FM2D_CAP_ROUND);
    fm2d_set_stroke_color(c, FM_RGB(255, 210, 90));
    fm2d_begin_path(c);
    fm2d_round_rect(c, 60, 440, 360, 220, (float[]){ 40, 10 }, 2);
    fm2d_stroke(c);
    fm2d_set_line_dash(c, NULL, 0);

    /* pattern inside a clip ellipse, with blend modes */
    fm2d_save(c);
    fm2d_begin_path(c);
    fm2d_ellipse(c, 700, 550, 220, 130, sinf(t * 0.3f) * 0.3f, 0, TAU, 0);
    fm2d_clip(c, FM_FILL_NONZERO);
    fm2d_paint* pat = fm2d_paint_pattern(a->tex, FM2D_REPEAT);
    fm_affine   pm  = { 0.5f, 0, 0, 0.5f, t * 30, 0 };
    fm2d_paint_set_transform(pat, &pm);
    fm2d_set_fill_paint(c, pat);
    fm2d_fill_rect(c, 450, 400, 500, 300);
    fm2d_paint_release(pat);
    fm2d_set_composite_op(c, FM_OP_MULTIPLY);
    fm2d_set_fill_color(c, FM_RGB(120, 220, 255));
    fm2d_begin_path(c);
    fm2d_arc(c, 640 + cosf(t) * 60, 550, 90, 0, TAU, 0);
    fm2d_fill(c, FM_FILL_NONZERO);
    fm2d_set_composite_op(c, FM_OP_SCREEN);
    fm2d_set_fill_color(c, FM_RGB(255, 60, 90));
    fm2d_begin_path(c);
    fm2d_arc(c, 760 - cosf(t) * 60, 550, 90, 0, TAU, 0);
    fm2d_fill(c, FM_FILL_NONZERO);
    fm2d_restore(c);

    /* bezier ribbon */
    fm2d_set_line_width(c, 3);
    fm2d_set_stroke_color(c, FM_RGBA(255, 255, 255, 180));
    for (int i = 0; i < 12; i++) {
        float k = (float)i / 11.0f;
        fm2d_begin_path(c);
        fm2d_move_to(c, 980, 420 + k * 260);
        fm2d_bezier_to(c, 1100, 380 + sinf(t + k * 3) * 120, 1150, 700 - cosf(t + k * 2) * 120, 1260,
                       440 + k * 240);
        fm2d_stroke(c);
    }
}

static void scene_blend(app* a)
{
    fm2d_ctx* c = a->c;
    fm2d_clear(a->c, FM_RGB(40, 40, 40));
    /* checkerboard background shows transparency */
    for (int y = 0; y < H; y += 16)
        for (int x = 0; x < W; x += 16) {
            fm2d_set_fill_color(c, ((x ^ y) & 16) ? FM_RGB(90, 90, 90) : FM_RGB(60, 60, 60));
            fm2d_fill_rect(c, (float)x, (float)y, 16, 16);
        }
    const int cols = 7, tw = 180, th = 175;
    for (int op = 0; op < FM_OP_COUNT; op++) {
        /* one surface per tile: in deferred mode drawImage reads the tile at
         * flush time, so tiles must not be reused within a frame */
        fm2d_ctx* tc = a->tile_ctx;
        fm2d_set_target(tc, a->tiles[op]);
        fm_surface_clear(a->tiles[op], 0);
        fm2d_reset(tc);
        /* destination: blue disc */
        fm2d_set_fill_color(tc, FM_RGBA(40, 120, 255, 230));
        fm2d_begin_path(tc);
        fm2d_arc(tc, 65, 70, 55, 0, TAU, 0);
        fm2d_fill(tc, FM_FILL_NONZERO);
        /* source: gradient square with the op under test */
        fm2d_set_composite_op(tc, (fm_blend_op)op);
        fm2d_paint* g = fm2d_paint_linear(50, 40, 160, 150);
        fm2d_paint_add_stop(g, 0, FM_RGBA(255, 60, 40, 255));
        fm2d_paint_add_stop(g, 1, FM_RGBA(255, 230, 40, 180));
        fm2d_set_fill_paint(tc, g);
        fm2d_begin_path(tc);
        fm2d_round_rect(tc, 55 + sinf(a->t) * 10, 45, 100, 100, (float[]){ 12 }, 1);
        fm2d_fill(tc, FM_FILL_NONZERO);
        fm2d_paint_release(g);
        int col = op % cols, row = op / cols;
        fm2d_draw_image(c, a->tiles[op], (float)(col * tw + 10), (float)(row * th + 10));
    }
}

typedef struct ball {
    float x, y, vx, vy, r;
    fm_color col;
} ball;

static ball g_balls[65536];

static void scene_stress(app* a, float dt)
{
    fm2d_ctx* c = a->c;
    fm2d_clear(a->c, FM_RGB(8, 8, 12));
    static int inited = 0;
    if (!inited) {
        for (int i = 0; i < 65536; i++) {
            ball* b = &g_balls[i];
            b->x = rndf() * W;
            b->y = rndf() * H;
            b->vx = (rndf() - 0.5f) * 300;
            b->vy = (rndf() - 0.5f) * 300;
            b->r = 3 + rndf() * 20;
            b->col = FM_RGBA(rnd() & 255, rnd() & 255, rnd() & 255, 60 + (rnd() % 160));
        }
        inited = 1;
    }
    for (int i = 0; i < a->count; i++) {
        ball* b = &g_balls[i];
        b->x += b->vx * dt;
        b->y += b->vy * dt;
        if (b->x < 0 || b->x > W) b->vx = -b->vx;
        if (b->y < 0 || b->y > H) b->vy = -b->vy;
        fm2d_set_fill_color(c, b->col);
        fm2d_begin_path(c);
        fm2d_arc(c, b->x, b->y, b->r, 0, TAU, 0);
        fm2d_fill(c, FM_FILL_NONZERO);
    }
}

static void scene_texture(app* a)
{
    fm2d_ctx* c = a->c;
    fm2d_clear(a->c, FM_RGB(0, 0, 0));
    fm2d_set_image_smoothing(c, a->smooth);
    /* rotating, zooming textured quad: the fatmap classic */
    fm2d_save(c);
    fm2d_translate(c, W * 0.35f, H * 0.5f);
    fm2d_rotate(c, a->t * 0.4f);
    float z = 1.5f + sinf(a->t * 0.5f) * 1.2f;
    fm2d_scale(c, z, z);
    fm2d_paint* p = fm2d_paint_pattern(a->tex, FM2D_REPEAT);
    fm2d_set_fill_paint(c, p);
    fm2d_begin_path(c);
    fm2d_rect(c, -200, -200, 400, 400);
    fm2d_fill(c, FM_FILL_NONZERO);
    fm2d_paint_release(p);
    fm2d_restore(c);
    /* sprites: 1:1 blits and scaled, alpha */
    g_rng = 99;
    for (int i = 0; i < 200; i++) {
        float x = 800 + rndf() * 400 + sinf(a->t + (float)i) * 30, y = rndf() * (H - 64);
        if (i & 1)
            fm2d_draw_image(c, a->sprite, floorf(x), floorf(y));
        else {
            float s = 0.5f + rndf();
            fm2d_draw_image_scaled(c, a->sprite, x, y, 64 * s, 64 * s);
        }
    }
    fm2d_set_image_smoothing(c, 1);
}

static void scene_lines(app* a)
{
    fm2d_ctx* c = a->c;
    fm2d_clear(a->c, FM_RGB(5, 5, 10));
    fm2d_set_line_cap(c, FM2D_CAP_ROUND);
    for (int i = 0; i < 720; i++) {
        float ang = (float)i * TAU / 720.0f + a->t * 0.2f;
        float len = 150 + 150 * sinf((float)i * 0.05f + a->t);
        fm2d_set_stroke_color(c, FM_RGBA((uint8_t)(128 + 127 * cosf(ang)), (uint8_t)(128 + 127 * sinf(ang * 2)),
                                         255, 140));
        fm2d_set_line_width(c, 1.0f + (float)(i % 3));
        fm2d_begin_path(c);
        fm2d_move_to(c, 360, 360);
        fm2d_line_to(c, 360 + cosf(ang) * len, 360 + sinf(ang) * len);
        fm2d_stroke(c);
    }
    fm2d_set_line_join(c, FM2D_JOIN_ROUND);
    for (int k = 0; k < 6; k++) {
        fm2d_set_line_width(c, 1.0f + (float)k * 1.5f);
        fm2d_set_stroke_color(c, FM_RGBA(255, (uint8_t)(80 + k * 30), 60, 200));
        if (k == 5) {
            float d[2] = { 20, 12 };
            fm2d_set_line_dash(c, d, 2);
            fm2d_set_line_dash_offset(c, a->t * 60);
        }
        fm2d_begin_path(c);
        for (int i = 0; i <= 300; i++) {
            float x = 760 + (float)i * 1.6f;
            float y = 100 + (float)k * 105 + sinf((float)i * 0.07f + a->t * 2 + (float)k) * 40 *
                                                 cosf((float)i * 0.013f + a->t);
            if (i == 0)
                fm2d_move_to(c, x, y);
            else
                fm2d_line_to(c, x, y);
        }
        fm2d_stroke(c);
    }
    fm2d_set_line_dash(c, NULL, 0);
}

static void draw_compare_shapes(fm2d_ctx* c, float ox, float t)
{
    fm2d_set_fill_color(c, FM_RGB(255, 200, 60));
    fm2d_begin_path(c);
    fm2d_arc(c, ox + 150, 200, 100, 0, TAU, 0);
    fm2d_fill(c, FM_FILL_NONZERO);
    fm2d_set_stroke_color(c, FM_RGB(120, 220, 255));
    fm2d_set_line_width(c, 1);
    for (int i = 0; i < 24; i++) {
        float a = (float)i * TAU / 24 + t * 0.1f;
        fm2d_begin_path(c);
        fm2d_move_to(c, ox + 150, 500);
        fm2d_line_to(c, ox + 150 + cosf(a) * 180, 500 + sinf(a) * 180);
        fm2d_stroke(c);
    }
    fm2d_save(c);
    fm2d_translate(c, ox + 450, 300);
    fm2d_rotate(c, t * 0.3f);
    fm2d_set_fill_color(c, FM_RGBA(255, 80, 120, 220));
    fm2d_fill_rect(c, -80, -80, 160, 160);
    fm2d_restore(c);
}

static void scene_compare(app* a)
{
    fm2d_ctx* c = a->c;
    fm2d_clear(a->c, FM_RGB(20, 20, 26));
    fm2d_set_antialias(c, FM_AA_ANALYTIC);
    draw_compare_shapes(c, 0, a->t);
    fm2d_set_antialias(c, FM_AA_NONE);
    draw_compare_shapes(c, 640, a->t);
    fm2d_set_fill_color(c, FM_RGB(80, 80, 90));
    fm2d_fill_rect(c, 639, 0, 2, H);
}

/* ---- 3d scene ------------------------------------------------------------------- */

static fm3d_vertex v3(float x, float y, float z, float u, float v, fm_color c)
{
    fm3d_vertex r;
    memset(&r, 0, sizeof(r));
    r.x = x, r.y = y, r.z = z, r.u = u, r.v = v, r.color = c;
    return r;
}

static void make_cube(fm3d_vertex* out, float s)
{
    static const float P[8][3] = { { -1, -1, -1 }, { 1, -1, -1 }, { 1, 1, -1 }, { -1, 1, -1 },
                                   { -1, -1, 1 },  { 1, -1, 1 },  { 1, 1, 1 },  { -1, 1, 1 } };
    static const int   F[6][4] = { { 4, 5, 6, 7 }, { 1, 0, 3, 2 }, { 0, 4, 7, 3 },
                                   { 5, 1, 2, 6 }, { 7, 6, 2, 3 }, { 0, 1, 5, 4 } };
    static const float shade[6] = { 1.0f, 0.55f, 0.7f, 0.85f, 1.0f, 0.45f }; /* baked light until T&L */
    const float        uv[4][2] = { { 0, 0 }, { 1, 0 }, { 1, 1 }, { 0, 1 } };
    const int          tri[6]   = { 0, 1, 2, 0, 2, 3 };
    int                k        = 0;
    for (int f = 0; f < 6; f++) {
        uint32_t g = (uint32_t)(255 * shade[f]);
        for (int i = 0; i < 6; i++) {
            const float* p = P[F[f][tri[i]]];
            out[k++]       = v3(p[0] * s, p[1] * s, p[2] * s, uv[tri[i]][0], uv[tri[i]][1], FM_RGB(g, g, g));
        }
    }
}

static void scene_3d(app* a)
{
    fm3d_ctx* c = a->c3;
    fm3d_set_target(c, a->fb, fm_swapchain_depth(a->sc));
    fm3d_clear_color(c, FM_RGB(18, 22, 38));
    fm3d_clear_depth(c, 1.0f);
    float   t    = a->t;
    fm_mat4 proj = fm_perspective(fm_radians(60), (float)W / H, 0.1f, 300.0f);
    fm_mat4 view = fm_lookat(fm_v3(sinf(t * 0.2f) * 14, 5 + sinf(t * 0.3f) * 2, cosf(t * 0.2f) * 14),
                             fm_v3(0, 0, 0), fm_v3(0, 1, 0));
    fm_mat4 id   = fm_mat4_identity();
    fm3d_set_projection(c, &proj);
    fm3d_set_view(c, &view);
    fm3d_set_model(c, &id);
    fm3d_set_perspective_correct(c, a->persp3d);
    fm3d_set_depth_test(c, FM3D_LESS, 1);
    fm3d_set_cull(c, FM3D_CULL_BACK, FM3D_FRONT_CCW);
    fm3d_set_blend(c, FM_OP_SRC_OVER);
    fm3d_set_texenv(c, FM3D_TEXENV_MODULATE);
    static const fm3d_filter filters[3] = { FM3D_FILTER_NEAREST, FM3D_FILTER_BILINEAR, FM3D_FILTER_TRILINEAR };
    fm3d_filter              f          = filters[a->filter3d % 3];

    /* floor grid */
    enum { G = 48 };
    static fm3d_vertex fv[(G + 1) * (G + 1)];
    static uint32_t    fi[G * G * 6];
    static int         built = 0;
    if (!built) {
        for (int z = 0; z <= G; z++)
            for (int x = 0; x <= G; x++)
                fv[z * (G + 1) + x] = v3((float)x - G / 2, -1.5f, (float)z - G / 2, (float)x * 0.5f,
                                         (float)z * 0.5f, 0xffffffffu);
        int k = 0;
        for (int z = 0; z < G; z++)
            for (int x = 0; x < G; x++) {
                uint32_t i0 = (uint32_t)(z * (G + 1) + x), i1 = i0 + 1, i2 = i0 + G + 1, i3 = i2 + 1;
                fi[k++] = i0, fi[k++] = i2, fi[k++] = i1, fi[k++] = i1, fi[k++] = i2, fi[k++] = i3;
            }
        built = 1;
    }
    fm3d_sampler fs = { f, FM_WRAP_REPEAT, FM_WRAP_REPEAT, 0, FM_WRAP_REPEAT };
    fm3d_set_texture(c, a->floor_tex, &fs);
    fm3d_draw_indexed(c, fv, (G + 1) * (G + 1), fi, G * G * 6);

    /* rotating crates */
    fm3d_vertex  cube[36];
    fm3d_sampler cs = { f == FM3D_FILTER_TRILINEAR ? FM3D_FILTER_TRILINEAR : f, FM_WRAP_CLAMP, FM_WRAP_CLAMP, 0, FM_WRAP_CLAMP };
    make_cube(cube, 0.7f);
    fm3d_set_texture(c, a->crate_tex, &cs);
    for (int z = -3; z <= 3; z++)
        for (int x = -3; x <= 3; x++) {
            float   h = sinf(t + (float)(x * 3 + z)) * 0.6f;
            fm_mat4 m = fm_translate(fm_mat4_identity(), fm_v3((float)x * 3.0f, h, (float)z * 3.0f));
            m         = fm_rotate(m, t * 0.7f + (float)(x + z), fm_v3(0.3f, 1, 0.1f));
            fm3d_set_model(c, &m);
            fm3d_draw(c, cube, 36);
        }

    /* gouraud pyramid in the middle */
    fm3d_set_texture(c, NULL, NULL);
    fm_mat4 pm = fm_rotate(fm_translate(fm_mat4_identity(), fm_v3(0, 2.5f, 0)), -t, fm_v3(0, 1, 0));
    fm3d_set_model(c, &pm);
    fm_color    cr = FM_RGB(255, 60, 60), cg = FM_RGB(60, 255, 60), cb = FM_RGB(60, 60, 255), cy = FM_RGB(255, 255, 60);
    fm3d_vertex pyr[12] = { v3(0, 1.5f, 0, 0, 0, cy), v3(-1, -1, 1, 0, 0, cr),  v3(1, -1, 1, 0, 0, cg),
                            v3(0, 1.5f, 0, 0, 0, cy), v3(1, -1, 1, 0, 0, cg),   v3(0, -1, -1.2f, 0, 0, cb),
                            v3(0, 1.5f, 0, 0, 0, cy), v3(0, -1, -1.2f, 0, 0, cb), v3(-1, -1, 1, 0, 0, cr),
                            v3(-1, -1, 1, 0, 0, cr),  v3(0, -1, -1.2f, 0, 0, cb), v3(1, -1, 1, 0, 0, cg) };
    fm3d_draw(c, pyr, 12);

    /* alpha tested + blended billboards */
    fm3d_set_cull(c, FM3D_CULL_NONE, FM3D_FRONT_CCW);
    fm3d_set_texture(c, a->crate_tex, &cs);
    fm3d_set_alpha_test(c, FM3D_GREATER, 0.4f);
    for (int i = 0; i < 6; i++) {
        float   ang = (float)i / 6 * 6.2831853f + t * 0.3f;
        fm_mat4 m   = fm_translate(fm_mat4_identity(), fm_v3(cosf(ang) * 11, 1.0f, sinf(ang) * 11));
        fm3d_set_model(c, &m);
        fm3d_vertex q[6] = { v3(-1.5f, -1.5f, 0, 0, 1, 0xffffffffu), v3(1.5f, -1.5f, 0, 1, 1, 0xffffffffu),
                             v3(1.5f, 1.5f, 0, 1, 0, 0xffffffffu),   v3(-1.5f, -1.5f, 0, 0, 1, 0xffffffffu),
                             v3(1.5f, 1.5f, 0, 1, 0, 0xffffffffu),   v3(-1.5f, 1.5f, 0, 0, 0, 0xffffffffu) };
        fm3d_draw(c, q, 6);
    }
    fm3d_set_alpha_test(c, FM3D_ALWAYS, 0);
    fm3d_set_texture(c, NULL, NULL);
}

/* ---- troll scene (data/troll2.obj + JPG textures; local only, not in the repo: its
 * origin / license is unknown, see data/README.md) ---- */

typedef struct troll_part {
    obj_part*     p;
    fm3d_texture* tex;
    int           kind; /* 0 ground, 1 hill, 2 troll */
} troll_part;

typedef struct troll_scene {
    int           tried, ok;
    obj_model     model;
    troll_part    parts[8];
    int           nparts;
    fm3d_texture* tex_troll;
    fm3d_texture* tex_pedestal;
    fm3d_texture* tex_grass;
    float         center[3], radius;
} troll_scene;

static troll_scene g_troll;

static int find_data(const char* name, char* out, size_t cap)
{
    const char* base = SDL_GetBasePath();
    const char* dirs[] = { "data/", "../data/", "../../data/" };
    for (int pass = 0; pass < 2; pass++)
        for (int i = 0; i < 3; i++) {
            snprintf(out, cap, "%s%s%s", pass ? (base ? base : "") : "", dirs[i], name);
            FILE* f = fopen(out, "rb");
            if (f) {
                fclose(f);
                return 1;
            }
        }
    return 0;
}

static fm3d_texture* tex_from(fm_surface* s) /* takes ownership, builds mipmaps */
{
    if (!s) return NULL;
    fm3d_texture* t = fm3d_texture_create(s, 1);
    fm_surface_destroy(s);
    return t;
}

static fm3d_texture* load_tex(const char* name)
{
    char path[1024];
    if (!find_data(name, path, sizeof(path))) {
        printf("missing data/%s (see data/README.md)\n", name);
        return NULL;
    }
    fm_surface* s = img_load_file(path);
    if (!s) printf("cannot decode data/%s\n", name);
    return tex_from(s);
}

static fm_surface* load_img(const char* name)
{
    char path[1024];
    if (!find_data(name, path, sizeof(path))) {
        printf("missing data/%s (see data/README.md)\n", name);
        return NULL;
    }
    return img_load_file(path);
}

#define CH_R(p) (((p) >> 16) & 255u)
#define CH_G(p) (((p) >> 8) & 255u)
#define CH_B(p) ((p) & 255u)
static uint32_t sat_add(uint32_t a, uint32_t b) { return a + b > 255 ? 255 : a + b; }

/* troll diffuse: colors + emissive glow (saturating add), alpha from the
 * grey alpha map; the JPGs are opaque, so their ARGB is straight RGB */
static fm3d_texture* load_troll_diffuse(void)
{
    fm_surface*    c = load_img("colors.jpg");
    fm_surface*    e = load_img("emissive.jpg");
    fm_surface*    m = load_img("alpha.jpg");
    fm3d_texture*  t = NULL;
    if (c && e && m && e->width == c->width && e->height == c->height && m->width == c->width &&
        m->height == c->height) {
        uint8_t* rgba = (uint8_t*)malloc((size_t)c->width * (size_t)c->height * 4);
        for (int y = 0; rgba && y < c->height; y++) {
            const uint32_t *rc = fm_surface_row32(c, y), *re = fm_surface_row32(e, y), *rm = fm_surface_row32(m, y);
            uint8_t*        o  = rgba + (size_t)y * (size_t)c->width * 4;
            for (int x = 0; x < c->width; x++) {
                o[4 * x + 0] = (uint8_t)sat_add(CH_R(rc[x]), CH_R(re[x]));
                o[4 * x + 1] = (uint8_t)sat_add(CH_G(rc[x]), CH_G(re[x]));
                o[4 * x + 2] = (uint8_t)sat_add(CH_B(rc[x]), CH_B(re[x]));
                o[4 * x + 3] = (uint8_t)CH_R(rm[x]);
            }
        }
        if (rgba) t = tex_from(fm_surface_from_rgba8(rgba, c->width, c->height, c->width * 4));
        free(rgba);
    }
    fm_surface_destroy(c);
    fm_surface_destroy(e);
    fm_surface_destroy(m);
    return t;
}

/* generated ground for the characters scene when data/R.jpg is absent */
static fm3d_texture* make_grass(void)
{
    fm_surface* s = fm_surface_create(256, 256, FM_FORMAT_ARGB32);
    uint32_t    h = 2166136261u;
    for (int y = 0; y < 256; y++)
        for (int x = 0; x < 256; x++) {
            h ^= (uint32_t)x * 73856093u ^ (uint32_t)y * 19349663u;
            h *= 16777619u;
            int k                     = (int)(h >> 26);                 /* 0..63 of noise */
            int b                     = ((x >> 5) + (y >> 5)) & 1 ? 8 : 0; /* faint patches */
            fm_surface_row32(s, y)[x] = FM_RGB((uint8_t)(40 + k / 2 + b), (uint8_t)(92 + k + b), (uint8_t)(34 + k / 3));
        }
    return tex_from(s);
}
static fm3d_texture* g_grass_fallback;

static void troll_load(void)
{
    troll_scene* T = &g_troll;
    T->tried       = 1;
    char path[1024];
    if (!find_data("troll2.obj", path, sizeof(path)) || !obj_load(path, &T->model)) {
        printf("troll: data/troll2.obj not found\n");
        return;
    }
    uint64_t t0     = fm_time_ns();
    T->tex_troll    = load_troll_diffuse();
    T->tex_pedestal = load_tex("pedestal.jpg");
    T->tex_grass    = load_tex("R.jpg");
#if !FM_FEATURE_TNL
    /* no fixed function lighting in this build: bake the directional light */
    fm_vec3 L = fm_v3_normalize(fm_v3(0.4f, 1.0f, 0.6f));
#endif
    int     tris = 0;
    for (int i = 0; i < T->model.nparts && T->nparts < 8; i++) {
        obj_part*   p    = &T->model.parts[i];
        troll_part* tp   = &T->parts[T->nparts++];
        tp->p            = p;
        tp->kind         = !strcmp(p->group, "groundplane") ? 0 : (!strcmp(p->group, "hill") ? 1 : 2);
        tp->tex          = tp->kind == 0 ? T->tex_grass : (tp->kind == 1 ? T->tex_pedestal : T->tex_troll);
        tris += p->ni / 3;
        for (int v = 0; v < p->nv; v++) {
            fm3d_vertex* q = &p->v[v];
            if (tp->kind == 0) { /* planar grass mapping, tiled */
                q->u = q->x / 80.0f;
                q->v = q->z / 80.0f;
            }
#if FM_FEATURE_TNL
            q->color = FM_RGB(255, 255, 255); /* lit per frame by T&L (color material) */
#else
            fm_vec3  n  = fm_v3_normalize(fm_v3(q->nx, q->ny, q->nz));
            float    d  = fm_v3_dot(n, L);
            float    li = 0.38f + 0.72f * (d > 0 ? d : 0);
            if (li > 1.0f) li = 1.0f;
            uint32_t g  = (uint32_t)(li * 255.0f);
            q->color    = FM_RGB(g, g, g);
#endif
        }
    }
    /* frame the troll (the tallest part) */
    for (int k = 0; k < 3; k++) T->center[k] = 0;
    for (int i = 0; i < T->nparts; i++)
        if (T->parts[i].kind == 2) {
            float mn[3] = { 1e30f, 1e30f, 1e30f }, mx[3] = { -1e30f, -1e30f, -1e30f };
            for (int v = 0; v < T->parts[i].p->nv; v++) {
                const float* q = &T->parts[i].p->v[v].x;
                for (int k = 0; k < 3; k++) {
                    mn[k] = q[k] < mn[k] ? q[k] : mn[k];
                    mx[k] = q[k] > mx[k] ? q[k] : mx[k];
                }
            }
            for (int k = 0; k < 3; k++) T->center[k] = (mn[k] + mx[k]) * 0.5f;
            T->radius = (mx[1] - mn[1]) * 0.5f;
        }
    if (T->radius <= 0) T->radius = 60;
    T->ok = 1;
    printf("troll: %d parts, %d triangles, loaded in %.0f ms\n", T->nparts, tris, (double)(fm_time_ns() - t0) / 1e6);
}

/* sun: directional light + ambient (the same formula the lean build bakes:
 * 0.38 ambient + 0.72 diffuse, color material) */
static void sun_on(fm3d_ctx* c, fm_vec3 towards_light, float ambient, float diffuse, float specular)
{
#if FM_FEATURE_TNL
    fm3d_light l = fm3d_light_default(FM3D_LIGHT_DIRECTIONAL);
    l.direction  = fm_v3_negate(fm_v3_normalize(towards_light));
    l.diffuse    = fm_v3(diffuse, diffuse, diffuse);
    l.specular   = fm_v3(specular, specular, specular);
    fm3d_set_light(c, 0, &l);
    fm3d_set_ambient_light(c, fm_v3(ambient, ambient, ambient));
    fm3d_material m = fm3d_material_default();
    m.specular      = fm_v3(1, 1, 1);
    m.shininess     = 32;
    fm3d_set_material(c, &m);
    fm3d_set_color_material(c, 1);
    fm3d_set_lighting(c, 1);
#else
    (void)c, (void)towards_light, (void)ambient, (void)diffuse, (void)specular;
#endif
}

static void sun_off(fm3d_ctx* c)
{
#if FM_FEATURE_TNL
    fm3d_set_lighting(c, 0);
#else
    (void)c;
#endif
}

static void scene_troll(app* a)
{
    troll_scene* T = &g_troll;
    fm3d_ctx*    c = a->c3;
    if (!T->tried) troll_load();
    fm3d_set_target(c, a->fb, fm_swapchain_depth(a->sc));
    fm3d_clear_color(c, FM_RGB(120, 160, 210));
    fm3d_clear_depth(c, 1.0f);
    if (!T->ok) return;
    float   ang  = a->t * 0.25f;
    float   dist = T->radius * 3.6f;
    fm_vec3 ctr  = fm_v3(T->center[0], T->center[1], T->center[2]);
    fm_vec3 eye  = fm_v3(ctr.x + sinf(ang) * dist, ctr.y + T->radius * 0.6f, ctr.z + cosf(ang) * dist);
    fm_mat4 proj = fm_perspective(fm_radians(50), (float)W / H, 2.0f, 5000.0f);
    fm_mat4 view = fm_lookat(eye, ctr, fm_v3(0, 1, 0));
    fm_mat4 id   = fm_mat4_identity();
    fm3d_set_projection(c, &proj);
    fm3d_set_view(c, &view);
    fm3d_set_model(c, &id);
    fm3d_set_perspective_correct(c, a->persp3d);
    fm3d_set_depth_test(c, FM3D_LESS, 1);
    fm3d_set_cull(c, FM3D_CULL_BACK, FM3D_FRONT_CCW);
    fm3d_set_blend(c, FM_OP_SRC_OVER);
    fm3d_set_texenv(c, FM3D_TEXENV_MODULATE);
    static const fm3d_filter filters[3] = { FM3D_FILTER_NEAREST, FM3D_FILTER_BILINEAR, FM3D_FILTER_TRILINEAR };
    fm3d_filter              f          = filters[a->filter3d % 3];
    sun_on(c, fm_v3(0.4f, 1.0f, 0.6f), 0.38f, 0.72f, 0.0f);
    for (int i = 0; i < T->nparts; i++) {
        troll_part*  tp = &T->parts[i];
        fm3d_sampler s  = { f, tp->kind == 2 ? FM_WRAP_CLAMP : FM_WRAP_REPEAT,
                            tp->kind == 2 ? FM_WRAP_CLAMP : FM_WRAP_REPEAT, 0, FM_WRAP_REPEAT };
        fm3d_set_texture(c, tp->tex, &s);
        /* the troll texture has cut-out alpha (straps, fringes) */
        fm3d_set_alpha_test(c, tp->kind == 2 ? FM3D_GREATER : FM3D_ALWAYS, 0.5f);
        fm3d_set_cull(c, tp->kind == 2 ? FM3D_CULL_NONE : FM3D_CULL_BACK, FM3D_FRONT_CCW);
        fm3d_draw_indexed(c, tp->p->v, tp->p->nv, tp->p->idx, tp->p->ni);
    }
    sun_off(c);
    fm3d_set_alpha_test(c, FM3D_ALWAYS, 0);
    fm3d_set_texture(c, NULL, NULL);
}

/* ---- animated characters (data/Fox.glb, data/CesiumMan.glb: glTF sample assets) ---- */

typedef struct character {
    gltf_model    m;
    fm3d_texture* tex;
    int           ok;
    float         scale, cx, cz, floor_y; /* normalize to a target height, stand on y = 0 */
    fm_mat4       bones[256];
    fm3d_vertex*  posed; /* the skinned vertices of the current frame */
} character;

/* vertex blending on the CPU (application side; fatmap only draws): per
 * vertex M = sum w_k * bones[joint_k], position M * p, normal M * n */
static void character_skin(character* ch)
{
    const gltf_model* m = &ch->m;
    if (!ch->posed) ch->posed = (fm3d_vertex*)malloc((size_t)m->nv * sizeof(fm3d_vertex));
    if (!ch->posed) return;
    for (int i = 0; i < m->nv; i++) {
        const fm3d_vertex*      v  = &m->v[i];
        const gltf_skin_vertex* sk = &m->skin[i];
        float                   M[16];
        for (int k = 0; k < 4; k++) {
            const float* b = &ch->bones[sk->joint[k] < m->njoints ? sk->joint[k] : 0].c[0].x;
            for (int e = 0; e < 16; e++) M[e] = k ? M[e] + sk->weight[k] * b[e] : sk->weight[k] * b[e];
        }
        fm3d_vertex* o = &ch->posed[i];
        *o             = *v;
        o->x  = M[0] * v->x + M[4] * v->y + M[8] * v->z + M[12];
        o->y  = M[1] * v->x + M[5] * v->y + M[9] * v->z + M[13];
        o->z  = M[2] * v->x + M[6] * v->y + M[10] * v->z + M[14];
        o->nx = M[0] * v->nx + M[4] * v->ny + M[8] * v->nz;
        o->ny = M[1] * v->nx + M[5] * v->ny + M[9] * v->nz;
        o->nz = M[2] * v->nx + M[6] * v->ny + M[10] * v->nz;
    }
}

static character g_fox, g_cesium;
static int       g_chars_tried;

static void character_load(character* ch, const char* glb, float height)
{
    char path[1024];
    if (!find_data(glb, path, sizeof(path)) || !gltf_load(path, &ch->m) || !ch->m.skin || ch->m.njoints > 256) {
        printf("characters: cannot load data/%s\n", glb);
        return;
    }
    ch->tex = ch->m.base_color ? fm3d_texture_create(ch->m.base_color, 1) : NULL; /* embedded image */
    /* rest pose bounds after skinning (the mesh may be authored in another space) */
    gltf_pose(&ch->m, -1, 0, ch->bones);
    float mn[3] = { 1e30f, 1e30f, 1e30f }, mx[3] = { -1e30f, -1e30f, -1e30f };
    for (int i = 0; i < ch->m.nv; i++) {
        const fm3d_vertex*      v  = &ch->m.v[i];
        const gltf_skin_vertex* sk = &ch->m.skin[i];
        fm_vec4                 p  = fm_v4(0, 0, 0, 0);
        for (int k = 0; k < 4; k++)
            p = fm_v4_add(p, fm_v4_scale(fm_mat4_mul_vec4(ch->bones[sk->joint[k]], fm_v4(v->x, v->y, v->z, 1)), sk->weight[k]));
        float q[3] = { p.x, p.y, p.z };
        for (int k = 0; k < 3; k++) {
            mn[k] = q[k] < mn[k] ? q[k] : mn[k];
            mx[k] = q[k] > mx[k] ? q[k] : mx[k];
        }
    }
    ch->scale   = height / (mx[1] - mn[1] > 1e-6f ? mx[1] - mn[1] : 1.0f);
    ch->cx      = (mn[0] + mx[0]) * 0.5f;
    ch->cz      = (mn[2] + mx[2]) * 0.5f;
    ch->floor_y = mn[1];
    ch->ok      = 1;
    printf("characters: %s %d verts, %d tris, %d joints, %d clips:", glb, ch->m.nv, ch->m.ni / 3, ch->m.njoints,
           ch->m.nanims);
    for (int a = 0; a < ch->m.nanims; a++) printf(" %s", ch->m.anims[a].name);
    printf("\n");
}

static void character_draw(fm3d_ctx* c, character* ch, int clip, float t, float radius, float speed, float phase)
{
    if (!ch->ok) return;
    gltf_pose(&ch->m, clip, t, ch->bones);
    character_skin(ch);
    if (!ch->posed) return;
    /* walk counter clockwise on a circle, facing the direction of travel (+Z forward) */
    float   ang = t * speed / radius + phase;
    fm_vec3 pos = fm_v3(cosf(ang) * radius, 0, sinf(ang) * radius);
    float   yaw = atan2f(-sinf(ang), cosf(ang)) + (speed < 0 ? 3.14159265f : 0.0f);
    fm_mat4 m   = fm_translate(fm_mat4_identity(), pos);
    m           = fm_rotate(m, yaw, fm_v3(0, 1, 0));
    m           = fm_scale(m, fm_v3(ch->scale, ch->scale, ch->scale));
    m           = fm_translate(m, fm_v3(-ch->cx, -ch->floor_y, -ch->cz));
    fm3d_set_model(c, &m);
    fm3d_sampler s = { FM3D_FILTER_TRILINEAR, FM_WRAP_REPEAT, FM_WRAP_REPEAT, 0, FM_WRAP_REPEAT };
    fm3d_set_texture(c, ch->tex, &s);
    fm3d_draw_indexed(c, ch->posed, ch->m.nv, ch->m.idx, ch->m.ni);
}

static void scene_characters(app* a)
{
    fm3d_ctx* c = a->c3;
    if (!g_chars_tried) {
        g_chars_tried = 1;
        character_load(&g_fox, "Fox.glb", 1.0f);
        character_load(&g_cesium, "CesiumMan.glb", 1.8f);
        if (!g_troll.tried) troll_load(); /* reuse its grass texture when present */
        if (!g_troll.tex_grass) g_grass_fallback = make_grass();
    }
    fm3d_set_target(c, a->fb, fm_swapchain_depth(a->sc));
    fm3d_clear_color(c, FM_RGB(130, 170, 220));
    fm3d_clear_depth(c, 1.0f);
    float   t    = a->t;
    fm_mat4 proj = fm_perspective(fm_radians(50), (float)W / H, 0.05f, 200.0f);
    fm_mat4 view = fm_lookat(fm_v3(sinf(t * 0.1f) * 7, 2.6f, cosf(t * 0.1f) * 7), fm_v3(0, 0.6f, 0), fm_v3(0, 1, 0));
    fm_mat4 id   = fm_mat4_identity();
    fm3d_set_projection(c, &proj);
    fm3d_set_view(c, &view);
    fm3d_set_model(c, &id);
    fm3d_set_perspective_correct(c, a->persp3d);
    fm3d_set_depth_test(c, FM3D_LESS, 1);
    fm3d_set_cull(c, FM3D_CULL_BACK, FM3D_FRONT_CCW);
    fm3d_set_blend(c, FM_OP_SRC_OVER);
    fm3d_set_texenv(c, FM3D_TEXENV_MODULATE);
    /* grass ground */
    fm_color     gc = FM_RGB(200, 210, 200);
    fm3d_vertex  g[6];
    const float  E = 20, UV = 10;
    float        P[4][2] = { { -E, -E }, { E, -E }, { E, E }, { -E, E } };
    int          o[6]    = { 0, 3, 1, 1, 3, 2 };
    for (int i = 0; i < 6; i++) {
        memset(&g[i], 0, sizeof(g[i]));
        g[i].x = P[o[i]][0], g[i].z = P[o[i]][1];
        g[i].u = (P[o[i]][0] + E) / (2 * E) * UV, g[i].v = (P[o[i]][1] + E) / (2 * E) * UV;
        g[i].color = gc;
        g[i].ny    = 1.0f;
    }
    fm3d_sampler gs = { FM3D_FILTER_TRILINEAR, FM_WRAP_REPEAT, FM_WRAP_REPEAT, 0, FM_WRAP_REPEAT };
    fm3d_set_texture(c, g_troll.tex_grass ? g_troll.tex_grass : g_grass_fallback, &gs);
    fm3d_draw(c, g, 6);
    sun_on(c, fm_v3(0.4f, 1.0f, 0.5f), 0.38f, 0.72f, 0.2f);
    /* the characters: skinned by the sandbox, lit by fatmap's T&L */
    fm3d_set_cull(c, FM3D_CULL_NONE, FM3D_FRONT_CCW);
    int fox_clip = g_fox.m.nanims ? a->fox_clip % g_fox.m.nanims : -1;
    character_draw(c, &g_fox, fox_clip, t, 2.2f, fox_clip == 2 ? 2.4f : (fox_clip == 1 ? 0.9f : 0.0f), 0.0f);
    character_draw(c, &g_cesium, 0, t, 3.4f, 1.1f, 2.0f);
    sun_off(c);
    fm3d_set_texture(c, NULL, NULL);
}

/* ---- helmet (data/DamagedHelmet.glb, Khronos glTF sample, static PBR mesh) ----
 * No lighting in fatmap yet: the texture is base color x ambient occlusion +
 * emissive, and a directional light fixed in world space is evaluated per
 * vertex on the CPU each frame into the vertex color (texenv modulate). */

typedef struct helmet {
    gltf_model    m;
    fm3d_texture* tex;
    fm3d_vertex*  lit;
    fm_mat4       base; /* mesh node matrix, then centered and scaled to unit size */
    int           tried, ok;
} helmet;

static helmet g_helmet;

static void helmet_load(void)
{
    helmet* hm = &g_helmet;
    hm->tried  = 1;
    char path[1024];
    if (!find_data("DamagedHelmet.glb", path, sizeof(path)) || !gltf_load(path, &hm->m) || !hm->m.base_color) {
        printf("helmet: cannot load data/DamagedHelmet.glb\n");
        return;
    }
    fm_surface* bc = hm->m.base_color;
    fm_surface* ao = hm->m.occlusion;
    fm_surface* em = hm->m.emissive;
    if (ao && (ao->width != bc->width || ao->height != bc->height)) ao = NULL;
    if (em && (em->width != bc->width || em->height != bc->height)) em = NULL;
    uint8_t* rgba = (uint8_t*)malloc((size_t)bc->width * (size_t)bc->height * 4);
    if (!rgba) return;
    for (int y = 0; y < bc->height; y++) {
        const uint32_t* rb = fm_surface_row32(bc, y);
        const uint32_t* ra = ao ? fm_surface_row32(ao, y) : NULL;
        const uint32_t* re = em ? fm_surface_row32(em, y) : NULL;
        uint8_t*        o  = rgba + (size_t)y * (size_t)bc->width * 4;
        for (int x = 0; x < bc->width; x++) {
            uint32_t occ = ra ? CH_R(ra[x]) : 255u; /* glTF occlusion: red channel */
            uint32_t e   = re ? re[x] : 0u;
            o[4 * x + 0] = (uint8_t)sat_add(CH_R(rb[x]) * occ / 255u, CH_R(e));
            o[4 * x + 1] = (uint8_t)sat_add(CH_G(rb[x]) * occ / 255u, CH_G(e));
            o[4 * x + 2] = (uint8_t)sat_add(CH_B(rb[x]) * occ / 255u, CH_B(e));
            o[4 * x + 3] = 255;
        }
    }
    hm->tex = tex_from(fm_surface_from_rgba8(rgba, bc->width, bc->height, bc->width * 4));
    free(rgba);
    /* bounds in node space -> center + scale to a 2 unit tall model */
    fm_mat4 mm = gltf_mesh_matrix(&hm->m);
    float   mn[3] = { 1e30f, 1e30f, 1e30f }, mx[3] = { -1e30f, -1e30f, -1e30f };
    for (int i = 0; i < hm->m.nv; i++) {
        fm_vec4 q = fm_mat4_mul_vec4(mm, fm_v4(hm->m.v[i].x, hm->m.v[i].y, hm->m.v[i].z, 1));
        float   w[3] = { q.x, q.y, q.z };
        for (int k = 0; k < 3; k++) {
            mn[k] = w[k] < mn[k] ? w[k] : mn[k];
            mx[k] = w[k] > mx[k] ? w[k] : mx[k];
        }
    }
    float ext = mx[1] - mn[1];
    for (int k = 0; k < 3; k += 2) ext = (mx[k] - mn[k]) > ext ? (mx[k] - mn[k]) : ext;
    float sc = 2.0f / (ext > 1e-6f ? ext : 1.0f);
    hm->base  = fm_scale(fm_mat4_identity(), fm_v3(sc, sc, sc));
    hm->base  = fm_translate(hm->base, fm_v3(-(mn[0] + mx[0]) * 0.5f, -(mn[1] + mx[1]) * 0.5f, -(mn[2] + mx[2]) * 0.5f));
    hm->base  = fm_mat4_mul(hm->base, mm);
    hm->lit   = (fm3d_vertex*)malloc((size_t)hm->m.nv * sizeof(fm3d_vertex));
    hm->ok    = hm->lit && hm->tex;
    printf("helmet: %d verts, %d tris, texture %dx%d\n", hm->m.nv, hm->m.ni / 3, bc->width, bc->height);
}

static void scene_helmet(app* a)
{
    helmet*   hm = &g_helmet;
    fm3d_ctx* c = a->c3;
    if (!hm->tried) helmet_load();
    fm3d_set_target(c, a->fb, fm_swapchain_depth(a->sc));
    fm3d_clear_color(c, FM_RGB(28, 30, 38));
    fm3d_clear_depth(c, 1.0f);
    if (!hm->ok) return;
    fm_mat4 proj  = fm_perspective(fm_radians(40), (float)W / H, 0.05f, 50.0f);
    fm_mat4 view  = fm_lookat(fm_v3(0, 0.3f, 4.2f), fm_v3(0, 0, 0), fm_v3(0, 1, 0));
    fm_mat4 model = fm_mat4_mul(fm_rotate(fm_mat4_identity(), a->t * 0.45f, fm_v3(0, 1, 0)), hm->base);
    const fm3d_vertex* verts = hm->m.v;
#if FM_FEATURE_TNL
    sun_on(c, fm_v3(-0.5f, 0.7f, 0.8f), 0.32f, 0.85f, 0.45f);
#else
    /* no T&L in this build: the same directional light on the CPU */
    fm_vec3 L = fm_v3_normalize(fm_v3(-0.5f, 0.7f, 0.8f));
    for (int i = 0; i < hm->m.nv; i++) {
        const fm3d_vertex* v = &hm->m.v[i];
        fm_vec4            n = fm_mat4_mul_vec4(model, fm_v4(v->nx, v->ny, v->nz, 0));
        fm_vec3            nw = fm_v3_normalize(fm_v3(n.x, n.y, n.z));
        float              d  = fm_v3_dot(nw, L);
        float              li = 0.32f + 0.85f * (d > 0 ? d : 0);
        uint32_t           g  = (uint32_t)((li > 1.0f ? 1.0f : li) * 255.0f);
        hm->lit[i]             = *v;
        hm->lit[i].color       = FM_RGB((uint8_t)g, (uint8_t)g, (uint8_t)g);
    }
    verts = hm->lit;
#endif
    fm3d_set_projection(c, &proj);
    fm3d_set_view(c, &view);
    fm3d_set_model(c, &model);
    fm3d_set_perspective_correct(c, a->persp3d);
    fm3d_set_depth_test(c, FM3D_LESS, 1);
    fm3d_set_cull(c, FM3D_CULL_BACK, FM3D_FRONT_CCW);
    fm3d_set_blend(c, FM_OP_SRC_OVER);
    fm3d_set_texenv(c, FM3D_TEXENV_MODULATE);
    fm3d_sampler s = { FM3D_FILTER_TRILINEAR, FM_WRAP_REPEAT, FM_WRAP_REPEAT, 0, FM_WRAP_REPEAT };
    fm3d_set_texture(c, hm->tex, &s);
    fm3d_draw_indexed(c, verts, hm->m.nv, hm->m.idx, hm->m.ni);
    sun_off(c);
    fm3d_set_texture(c, NULL, NULL);
}

/* ---- shaders (programmable stages + vertex buffer) ------------------------
 * Helmet: a fragment shader lights every pixel (Blinn-Phong on the
 * interpolated eye space normal, rim light, pulsing emissive map), drawn
 * from a vertex buffer; G switches to the fixed pipeline's per vertex T&L.
 * Flag: a vertex shader animates a {x, y} grid (custom vertex layout,
 * analytic normals), a fragment shader paints it procedurally. */

#if FM_FEATURE_SHADERS && FM_FEATURE_VBO
typedef struct sh_helmet_u {
    fm_mat4             mvp, mv;
    float               light[3]; /* eye space, towards the light */
    float               pulse;    /* emissive gain */
    const fm3d_texture* emissive;
    fm3d_sampler        samp;
} sh_helmet_u;

typedef struct sh_flag_u {
    fm_mat4 mvp, mv;
    float   light[3];
    float   t;
} sh_flag_u;

typedef struct flag_vtx {
    float x, y; /* 0..1 over the cloth */
} flag_vtx;

#if FM_FEATURE_SPIRV
typedef struct spv_helmet_u { /* std140: mat4 @0, mat4 @64, vec4 @128, float @144 */
    fm_mat4 mvp, mv;
    float   light[4];
    float   pulse, pad[3];
} spv_helmet_u;
typedef struct spv_flag_u {
    fm_mat4 mvp, mv;
    float   light[4];
    float   t, pad[3];
} spv_flag_u;
#endif

typedef struct shader_scene {
#if FM_FEATURE_SPIRV
    fm3d_spirv* spv_helmet;
    fm3d_spirv* spv_flag;
#endif
    int           init;
    fm3d_buffer*  helmet;   /* the helmet mesh, uploaded once */
    fm3d_texture* base_ao;  /* base color x occlusion, mipmapped */
    fm3d_texture* emissive;
    flag_vtx*     flag;
    uint32_t*     flag_idx;
    int           flag_nv, flag_ni;
} shader_scene;

static shader_scene g_sh;

/* varyings: 0 u, 1 v, 2..4 eye position, 5..7 eye normal */
static void sh_helmet_vs(const fm3d_vs_io* io)
{
    const sh_helmet_u* U = (const sh_helmet_u*)io->uniforms;
    for (int i = 0; i < io->count; i++) {
        const fm3d_vertex* v = (const fm3d_vertex*)((const char*)io->vertices + (size_t)i * (size_t)io->stride);
        float*             o = io->pos + (size_t)i * (size_t)io->out_stride;
        float*             q = io->varyings + (size_t)i * (size_t)io->out_stride;
        fm_vec4            p = fm_mat4_mul_vec4(U->mvp, fm_v4(v->x, v->y, v->z, 1));
        fm_vec4            e = fm_mat4_mul_vec4(U->mv, fm_v4(v->x, v->y, v->z, 1));
        fm_vec4            n = fm_mat4_mul_vec4(U->mv, fm_v4(v->nx, v->ny, v->nz, 0)); /* uniform scale */
        o[0] = p.x, o[1] = p.y, o[2] = p.z, o[3] = p.w;
        q[0] = v->u, q[1] = v->v;
        q[2] = e.x, q[3] = e.y, q[4] = e.z;
        q[5] = n.x, q[6] = n.y, q[7] = n.z;
    }
}

static float sh_clamp(float x) { return x < 0 ? 0 : (x > 1 ? 1 : x); }

static void sh_helmet_fs(const fm3d_fs_io* io)
{
    const sh_helmet_u* U = (const sh_helmet_u*)io->uniforms;
    float              br[FM3D_BATCH_PIXELS], bg[FM3D_BATCH_PIXELS], bb[FM3D_BATCH_PIXELS], ba[FM3D_BATCH_PIXELS];
    float              er[FM3D_BATCH_PIXELS], eg[FM3D_BATCH_PIXELS], eb[FM3D_BATCH_PIXELS], ea[FM3D_BATCH_PIXELS];
    /* mipmapped (trilinear) from the quad derivatives of u, v */
    fm3d_sample_batch(io, io->texture, io->sampler, io->varyings[0], io->varyings[1], br, bg, bb, ba);
    if (U->emissive)
        fm3d_sample_batch(io, U->emissive, &U->samp, io->varyings[0], io->varyings[1], er, eg, eb, ea);
    else
        for (int i = 0; i < FM3D_BATCH_PIXELS; i++) er[i] = eg[i] = eb[i] = ea[i] = 0.0f;
    const float lx = U->light[0], ly = U->light[1], lz = U->light[2];
    for (int i = 0; i < FM3D_BATCH_PIXELS; i++) {
        if (!io->mask[i] || (i % FM3D_BATCH_COLS) >= io->cols) continue;
        float nx = io->varyings[5][i], ny = io->varyings[6][i], nz = io->varyings[7][i];
        float nl = 1.0f / sqrtf(nx * nx + ny * ny + nz * nz + 1e-20f);
        nx *= nl, ny *= nl, nz *= nl;
        float vx = -io->varyings[2][i], vy = -io->varyings[3][i], vz = -io->varyings[4][i];
        float vl = 1.0f / sqrtf(vx * vx + vy * vy + vz * vz + 1e-20f);
        vx *= vl, vy *= vl, vz *= vl;
        float ndl = nx * lx + ny * ly + nz * lz;
        ndl       = ndl > 0 ? ndl : 0;
        float hx = lx + vx, hy = ly + vy, hz = lz + vz, hl = 1.0f / sqrtf(hx * hx + hy * hy + hz * hz + 1e-20f);
        float ndh = (nx * hx + ny * hy + nz * hz) * hl;
        float sp  = ndl > 0 && ndh > 0 ? powf(ndh, 48.0f) * 0.7f : 0.0f;
        float ndv = nx * vx + ny * vy + nz * vz;
        float rim = powf(1.0f - (ndv > 0 ? ndv : 0), 3.0f) * 0.55f;
        float lit = 0.16f + 0.9f * ndl;
        io->out[0][i] = sh_clamp(br[i] * lit + sp + rim * 0.30f + er[i] * U->pulse);
        io->out[1][i] = sh_clamp(bg[i] * lit + sp + rim * 0.55f + eg[i] * U->pulse);
        io->out[2][i] = sh_clamp(bb[i] * lit + sp + rim * 1.00f + eb[i] * U->pulse);
        io->out[3][i] = 1.0f;
    }
}

/* flag cloth: pinned at x = 0, travelling wave; varyings 0 u, 1 v, 2..4 eye normal */
static void sh_flag_vs(const fm3d_vs_io* io)
{
    const sh_flag_u* U = (const sh_flag_u*)io->uniforms;
    for (int i = 0; i < io->count; i++) {
        const flag_vtx* v  = (const flag_vtx*)((const char*)io->vertices + (size_t)i * (size_t)io->stride);
        float           ph = 7.0f * v->x - 3.2f * U->t + 1.3f * v->y;
        float           a  = 0.16f * v->x; /* amplitude grows away from the pole */
        float           X = v->x * 2.0f, Y = v->y * 1.2f, Z = a * sinf(ph);
        /* dZ/dX, dZ/dY in world units */
        float dzdx = (0.16f * sinf(ph) + a * 7.0f * cosf(ph)) / 2.0f, dzdy = (a * 1.3f * cosf(ph)) / 1.2f;
        fm_vec4 p  = fm_mat4_mul_vec4(U->mvp, fm_v4(X, Y, Z, 1));
        fm_vec4 n  = fm_mat4_mul_vec4(U->mv, fm_v4(-dzdx, -dzdy, 1, 0));
        float*  o  = io->pos + (size_t)i * (size_t)io->out_stride;
        float*  q  = io->varyings + (size_t)i * (size_t)io->out_stride;
        o[0] = p.x, o[1] = p.y, o[2] = p.z, o[3] = p.w;
        q[0] = v->x, q[1] = v->y;
        q[2] = n.x, q[3] = n.y, q[4] = n.z;
    }
}

/* three bands with a checker hoist */
static void sh_flag_pattern(float u, float v, float* c)
{
    if (u < 0.3f && v > 0.45f) {
        int k = ((int)(u * 20.0f) + (int)(v * 12.0f)) & 1;
        c[0] = k ? 0.95f : 0.1f, c[1] = k ? 0.95f : 0.1f, c[2] = k ? 0.95f : 0.12f;
    } else if (v > 0.66f) {
        c[0] = 0.95f, c[1] = 0.55f, c[2] = 0.1f;
    } else if (v > 0.33f) {
        c[0] = 0.92f, c[1] = 0.92f, c[2] = 0.88f;
    } else {
        c[0] = 0.15f, c[1] = 0.4f, c[2] = 0.85f;
    }
}

static void sh_flag_fs(const fm3d_fs_io* io)
{
    const sh_flag_u* U = (const sh_flag_u*)io->uniforms;
    /* 4 rotated grid samples per pixel, spread by the screen derivatives
     * (fm3d_ddx / fm3d_ddy): anti-aliased pattern edges */
    static const float ox[4] = { -0.125f, 0.375f, 0.125f, -0.375f }, oy[4] = { -0.375f, -0.125f, 0.375f, 0.125f };
    const float*       Uu = io->varyings[0];
    const float*       Vv = io->varyings[1];
    for (int i = 0; i < FM3D_BATCH_PIXELS; i++) {
        if (!io->mask[i] || (i % FM3D_BATCH_COLS) >= io->cols) continue;
        float u = Uu[i], v = Vv[i];
        float dux = fm3d_ddx(Uu, i), duy = fm3d_ddy(Uu, i), dvx = fm3d_ddx(Vv, i), dvy = fm3d_ddy(Vv, i);
        float r = 0, g = 0, b = 0;
        for (int k = 0; k < 4; k++) {
            float c[3];
            sh_flag_pattern(u + dux * ox[k] + duy * oy[k], v + dvx * ox[k] + dvy * oy[k], c);
            r += 0.25f * c[0], g += 0.25f * c[1], b += 0.25f * c[2];
        }
        float nx = io->varyings[2][i], ny = io->varyings[3][i], nz = io->varyings[4][i];
        float nl = 1.0f / sqrtf(nx * nx + ny * ny + nz * nz + 1e-20f);
        float d  = (nx * U->light[0] + ny * U->light[1] + nz * U->light[2]) * nl;
        float li = 0.25f + 0.85f * (d < 0 ? -d : d); /* two sided cloth */
        io->out[0][i] = sh_clamp(r * li), io->out[1][i] = sh_clamp(g * li), io->out[2][i] = sh_clamp(b * li);
        io->out[3][i] = 1.0f;
    }
}

/* straight RGBA8 copy of a (possibly occlusion multiplied) base color */
static fm_surface* sh_compose(const fm_surface* bc, const fm_surface* ao)
{
    uint8_t* rgba = (uint8_t*)malloc((size_t)bc->width * (size_t)bc->height * 4);
    if (!rgba) return NULL;
    for (int y = 0; y < bc->height; y++) {
        const uint32_t* rb = fm_surface_row32(bc, y);
        const uint32_t* ra = ao ? fm_surface_row32(ao, y) : NULL;
        uint8_t*        o  = rgba + (size_t)y * (size_t)bc->width * 4;
        for (int x = 0; x < bc->width; x++) {
            uint32_t occ = ra ? CH_R(ra[x]) : 255u;
            o[4 * x + 0] = (uint8_t)(CH_R(rb[x]) * occ / 255u);
            o[4 * x + 1] = (uint8_t)(CH_G(rb[x]) * occ / 255u);
            o[4 * x + 2] = (uint8_t)(CH_B(rb[x]) * occ / 255u);
            o[4 * x + 3] = 255;
        }
    }
    fm_surface* s = fm_surface_from_rgba8(rgba, bc->width, bc->height, bc->width * 4);
    free(rgba);
    return s;
}

static void sh_init(void)
{
    g_sh.init  = 1;
#if FM_FEATURE_SPIRV
    {
        char                     err[256];
        const fm3d_vertex_attrib ha[3] = { { 0, 3, 0 }, { 1, 3, 12 }, { 2, 2, 24 } }; /* fm3d_vertex */
        const fm3d_vertex_attrib fa[1] = { { 0, 2, 0 } };                              /* flag_vtx */
        g_sh.spv_helmet = fm3d_spirv_create(spv_helmet_vert, sizeof(spv_helmet_vert) / 4, spv_helmet_frag,
                                            sizeof(spv_helmet_frag) / 4, ha, 3, err, sizeof(err));
        if (!g_sh.spv_helmet) printf("shaders scene: helmet SPIR-V: %s\n", err);
        g_sh.spv_flag = fm3d_spirv_create(spv_flag_vert, sizeof(spv_flag_vert) / 4, spv_flag_frag, sizeof(spv_flag_frag) / 4,
                                          fa, 1, err, sizeof(err));
        if (!g_sh.spv_flag) printf("shaders scene: flag SPIR-V: %s\n", err);
    }
#endif
    helmet* hm = &g_helmet;
    if (hm->ok) {
        g_sh.helmet  = fm3d_buffer_create(hm->m.v, hm->m.nv, hm->m.idx, hm->m.ni);
        const fm_surface* ao = hm->m.occlusion;
        if (ao && (ao->width != hm->m.base_color->width || ao->height != hm->m.base_color->height)) ao = NULL;
        g_sh.base_ao  = tex_from(sh_compose(hm->m.base_color, ao)); /* full mip chain */
        g_sh.emissive = hm->m.emissive ? fm3d_texture_create(hm->m.emissive, 1) : NULL;
    }
    enum { FX = 48, FY = 24 };
    g_sh.flag_nv  = (FX + 1) * (FY + 1);
    g_sh.flag_ni  = FX * FY * 6;
    g_sh.flag     = (flag_vtx*)malloc((size_t)g_sh.flag_nv * sizeof(flag_vtx));
    g_sh.flag_idx = (uint32_t*)malloc((size_t)g_sh.flag_ni * sizeof(uint32_t));
    if (!g_sh.flag || !g_sh.flag_idx) return;
    for (int y = 0; y <= FY; y++)
        for (int x = 0; x <= FX; x++) {
            g_sh.flag[y * (FX + 1) + x].x = (float)x / FX;
            g_sh.flag[y * (FX + 1) + x].y = (float)y / FY;
        }
    int k = 0;
    for (int y = 0; y < FY; y++)
        for (int x = 0; x < FX; x++) {
            uint32_t a = (uint32_t)(y * (FX + 1) + x), b = a + 1, c = a + FX + 1, d = c + 1;
            g_sh.flag_idx[k++] = a, g_sh.flag_idx[k++] = b, g_sh.flag_idx[k++] = d;
            g_sh.flag_idx[k++] = a, g_sh.flag_idx[k++] = d, g_sh.flag_idx[k++] = c;
        }
}

static void sh_free(void)
{
#if FM_FEATURE_SPIRV
    fm3d_spirv_destroy(g_sh.spv_helmet);
    fm3d_spirv_destroy(g_sh.spv_flag);
#endif
    fm3d_buffer_release(g_sh.helmet);
    fm3d_texture_release(g_sh.base_ao);
    fm3d_texture_release(g_sh.emissive);
    free(g_sh.flag);
    free(g_sh.flag_idx);
    memset(&g_sh, 0, sizeof(g_sh));
}
#endif

static void scene_shaders(app* a)
{
    helmet*   hm = &g_helmet;
    fm3d_ctx* c  = a->c3;
    if (!hm->tried) helmet_load();
    fm3d_set_target(c, a->fb, fm_swapchain_depth(a->sc));
    fm3d_clear_color(c, FM_RGB(22, 24, 34));
    fm3d_clear_depth(c, 1.0f);
#if !(FM_FEATURE_SHADERS && FM_FEATURE_VBO)
    static int told;
    if (!told) printf("shaders scene: this build has no programmable stages / vertex buffers (-Dshaders, -Dvbo)\n");
    told = 1;
    (void)hm;
#else
    if (!g_sh.init) sh_init();
    fm_mat4 proj = fm_perspective(fm_radians(40), (float)W / H, 0.05f, 50.0f);
    fm_mat4 view = fm_lookat(fm_v3(0.4f, 0.35f, 4.6f), fm_v3(0.4f, 0.1f, 0), fm_v3(0, 1, 0));
    fm_mat4 id   = fm_mat4_identity();
    fm3d_set_projection(c, &proj);
    fm3d_set_view(c, &view);
    fm3d_set_perspective_correct(c, a->persp3d);
    fm3d_set_depth_test(c, FM3D_LESS, 1);
    fm3d_set_blend(c, FM_OP_SRC_OVER);
    /* the light orbits the scene (a marker shows where it is) */
    float   la = a->t * 0.9f;
    fm_vec3 Lw = fm_v3_normalize(fm_v3(cosf(la), 0.3f + 0.35f * sinf(la * 0.7f), sinf(la)));
    fm_vec4 Le = fm_mat4_mul_vec4(view, fm_v4(Lw.x, Lw.y, Lw.z, 0));
    fm_vec3 L  = fm_v3_normalize(fm_v3(Le.x, Le.y, Le.z));

    /* helmet */
    if (hm->ok && g_sh.helmet) {
        fm_mat4 model = fm_translate(fm_mat4_identity(), fm_v3(-0.75f, 0, 0));
        model         = fm_mat4_mul(fm_rotate(model, 0.6f + a->t * 0.12f, fm_v3(0, 1, 0)), hm->base);
        fm3d_set_model(c, &model);
        fm3d_set_cull(c, FM3D_CULL_BACK, FM3D_FRONT_CCW);
        fm3d_sampler s = { FM3D_FILTER_TRILINEAR, FM_WRAP_REPEAT, FM_WRAP_REPEAT, 0, FM_WRAP_REPEAT };
#if FM_FEATURE_SPIRV
        if (SH_IS_SPIRV(a->shader_mode) && g_sh.spv_helmet && g_sh.base_ao) {
            spv_helmet_u u;
            memset(&u, 0, sizeof(u));
            u.mv       = fm_mat4_mul(view, model);
            u.mvp      = fm_mat4_mul(proj, u.mv);
            u.light[0] = L.x, u.light[1] = L.y, u.light[2] = L.z;
            u.pulse    = 0.55f + 0.45f * sinf(a->t * 2.5f);
            fm3d_spirv_set_jit(g_sh.spv_helmet, a->shader_mode == SH_JIT); /* G: interpreted / JIT */
            fm3d_program pr = fm3d_spirv_program(g_sh.spv_helmet);
#  if FM_SANDBOX_AOT
            if (a->shader_mode == SH_AOT) pr = aot_helmet_program();
#  endif
            fm3d_set_program(c, &pr);
            fm3d_set_uniforms(c, &u, sizeof(u));
            fm3d_set_texture_unit(c, 1, g_sh.base_ao, &s);
            fm3d_set_texture_unit(c, 2, g_sh.emissive, &s);
            fm3d_draw_buffer(c, g_sh.helmet, 0, fm3d_buffer_index_count(g_sh.helmet));
            fm3d_set_texture_unit(c, 1, NULL, NULL);
            fm3d_set_texture_unit(c, 2, NULL, NULL);
            fm3d_set_program(c, NULL);
        } else
#endif
        if (a->shader_mode != SH_FIXED && g_sh.base_ao) {
            sh_helmet_u u;
            u.mv       = fm_mat4_mul(view, model);
            u.mvp      = fm_mat4_mul(proj, u.mv);
            u.light[0] = L.x, u.light[1] = L.y, u.light[2] = L.z;
            u.pulse    = 0.55f + 0.45f * sinf(a->t * 2.5f);
            u.emissive = g_sh.emissive;
            u.samp     = s;
            fm3d_program pr = { sh_helmet_vs, sh_helmet_fs, 8, 0, NULL, 0, 0, 0, 0 };
            fm3d_set_program(c, &pr);
            fm3d_set_uniforms(c, &u, sizeof(u));
            fm3d_set_texture(c, g_sh.base_ao, &s);
            fm3d_draw_buffer(c, g_sh.helmet, 0, fm3d_buffer_index_count(g_sh.helmet));
            fm3d_set_program(c, NULL);
        } else { /* fixed function: the per vertex T&L of scene 0 */
            fm3d_sampler tr = { FM3D_FILTER_TRILINEAR, FM_WRAP_REPEAT, FM_WRAP_REPEAT, 0, FM_WRAP_REPEAT };
            fm3d_set_texenv(c, FM3D_TEXENV_MODULATE);
            fm3d_set_texture(c, hm->tex, &tr);
            sun_on(c, Lw, 0.32f, 0.85f, 0.45f); /* the same moving light, per vertex */
            fm3d_draw_buffer(c, g_sh.helmet, 0, fm3d_buffer_index_count(g_sh.helmet));
            sun_off(c);
        }
        fm3d_set_texture(c, NULL, NULL);
    }

    /* flag: vertex shader on a custom {x, y} vertex layout */
    if (g_sh.flag) {
        fm_mat4 model = fm_translate(fm_mat4_identity(), fm_v3(0.55f, -0.45f, -0.6f));
        model         = fm_rotate(model, -0.35f, fm_v3(0, 1, 0));
        sh_flag_u u;
        u.mv       = fm_mat4_mul(view, model);
        u.mvp      = fm_mat4_mul(proj, u.mv);
        u.light[0] = L.x, u.light[1] = L.y, u.light[2] = L.z;
        u.t        = a->t;
        fm3d_set_model(c, &id);
        fm3d_set_cull(c, FM3D_CULL_NONE, FM3D_FRONT_CCW);
        fm3d_program pr = { sh_flag_vs, sh_flag_fs, 5, 0, NULL, 0, 0, 0, 0 };
        fm3d_set_program(c, &pr);
        fm3d_set_uniforms(c, &u, sizeof(u));
#if FM_FEATURE_SPIRV
        if (SH_IS_SPIRV(a->shader_mode) && g_sh.spv_flag) {
            spv_flag_u su;
            memset(&su, 0, sizeof(su));
            su.mvp = u.mvp, su.mv = u.mv;
            for (int k = 0; k < 3; k++) su.light[k] = u.light[k];
            su.t = u.t;
            fm3d_spirv_set_jit(g_sh.spv_flag, a->shader_mode == SH_JIT);
            pr   = fm3d_spirv_program(g_sh.spv_flag);
#  if FM_SANDBOX_AOT
            if (a->shader_mode == SH_AOT) pr = aot_flag_program();
#  endif
            fm3d_set_program(c, &pr);
            fm3d_set_uniforms(c, &su, sizeof(su));
        }
#endif
        fm3d_draw_vertices(c, g_sh.flag, (int)sizeof(flag_vtx), g_sh.flag_nv, g_sh.flag_idx, g_sh.flag_ni);
        fm3d_set_program(c, NULL);
        /* the pole, fixed function */
        fm_color    pc = FM_RGB(150, 150, 160);
        fm3d_vertex pole[6];
        float       P[6][2] = { { -0.03f, -1.2f }, { 0.0f, -1.2f }, { 0.0f, 1.3f }, { -0.03f, -1.2f }, { 0.0f, 1.3f }, { -0.03f, 1.3f } };
        for (int i = 0; i < 6; i++) {
            memset(&pole[i], 0, sizeof(pole[i]));
            pole[i].x = P[i][0], pole[i].y = P[i][1], pole[i].color = pc;
        }
        fm3d_set_model(c, &model);
        fm3d_draw(c, pole, 6);
    }

    /* light marker: a small glowing octahedron in the light's direction */
    {
        fm_vec3     lp = fm_v3_add(fm_v3(-0.2f, 0.1f, 0), fm_v3_scale(Lw, 1.8f));
        fm_mat4     m  = fm_translate(fm_mat4_identity(), lp);
        m              = fm_rotate(m, a->t * 2.0f, fm_v3(0, 1, 0));
        const float r  = 0.09f;
        const float O[6][3] = { { r, 0, 0 }, { -r, 0, 0 }, { 0, r, 0 }, { 0, -r, 0 }, { 0, 0, r }, { 0, 0, -r } };
        const int   F[8][3] = { { 0, 2, 4 }, { 2, 1, 4 }, { 1, 3, 4 }, { 3, 0, 4 }, { 2, 0, 5 }, { 1, 2, 5 }, { 3, 1, 5 }, { 0, 3, 5 } };
        fm3d_vertex tri[24];
        for (int f = 0; f < 8; f++)
            for (int k = 0; k < 3; k++) {
                fm3d_vertex* v = &tri[3 * f + k];
                memset(v, 0, sizeof(*v));
                v->x = O[F[f][k]][0], v->y = O[F[f][k]][1], v->z = O[F[f][k]][2];
                v->color = f & 1 ? FM_RGB(255, 240, 150) : FM_RGB(255, 200, 60);
            }
        fm3d_set_model(c, &m);
        fm3d_set_cull(c, FM3D_CULL_NONE, FM3D_FRONT_CCW);
        fm3d_draw(c, tri, 24);
        fm3d_set_model(c, &id);
    }
#endif
}

/* "Seascape" by TDM (Shadertoy, CC BY-NC-SA 3.0; tests/spirv/seascape.frag):
 * a ray marched sea as one full screen fragment shader, rendered at a
 * fraction of the window and upscaled */
#if FM_FEATURE_SPIRV
typedef struct sea_u { /* std140: vec3 iResolution @0, float iTime @12, vec4 iMouse @16 */
    float res[3], time, mouse[4];
} sea_u;
static fm3d_spirv* g_sea;
static int         g_sea_tried;
static fm_surface* g_sea_fb;
#endif

static void scene_seascape(app* a)
{
#if FM_FEATURE_SPIRV
    fm3d_ctx* c = a->c3;
    if (!g_sea_tried) {
        char err[256];
        g_sea_tried = 1;
        g_sea = fm3d_spirv_create(NULL, 0, spv_seascape_frag, sizeof(spv_seascape_frag) / 4, NULL, 0, err, sizeof(err));
        if (!g_sea) printf("seascape: %s\n", err);
    }
    int sw = W / a->sea_div, sh = H / a->sea_div;
    if (!g_sea_fb || g_sea_fb->width != sw) {
        fm_surface_destroy(g_sea_fb);
        g_sea_fb = fm_surface_create(sw, sh, FM_FORMAT_ARGB32);
    }
    fm3d_set_target(c, g_sea_fb, NULL);
    fm3d_clear_color(c, FM_RGB(0, 0, 0));
    if (g_sea) {
        fm_mat4 pr = fm_ortho(0, (float)sw, (float)sh, 0, -1, 1), id = fm_mat4_identity();
        fm3d_set_projection(c, &pr);
        fm3d_set_view(c, &id);
        fm3d_set_model(c, &id);
        fm3d_set_depth_test(c, FM3D_ALWAYS, 0);
        fm3d_set_cull(c, FM3D_CULL_NONE, FM3D_FRONT_CCW);
        fm3d_set_blend(c, FM_OP_SRC_OVER); /* the shader writes alpha 1 */
        sea_u U;
        memset(&U, 0, sizeof(U));
        U.res[0] = (float)sw, U.res[1] = (float)sh, U.res[2] = 1.0f;
        U.time     = a->t;
        U.mouse[0] = a->mx / (float)a->sea_div, U.mouse[1] = a->my / (float)a->sea_div;
        fm3d_spirv_set_fast_math(g_sea, a->sea_fast);
        fm3d_spirv_set_jit(g_sea, a->shader_mode == SH_JIT);
        fm3d_program p = fm3d_spirv_program(g_sea);
#  if FM_SANDBOX_AOT
        if (a->shader_mode == SH_AOT) p = a->sea_fast ? aot_seascape_fast_program() : aot_seascape_program();
#  endif
        fm3d_set_program(c, &p);
        fm3d_set_uniforms(c, &U, sizeof(U));
        fm3d_vertex q[6];
        const float X[4] = { 0, (float)sw, (float)sw, 0 }, Y[4] = { 0, 0, (float)sh, (float)sh };
        const int   o[6] = { 0, 1, 2, 0, 2, 3 };
        for (int i = 0; i < 6; i++) {
            memset(&q[i], 0, sizeof(q[i]));
            q[i].x = X[o[i]], q[i].y = Y[o[i]], q[i].color = FM_RGB(255, 255, 255);
        }
        fm3d_draw(c, q, 6);
        fm3d_set_program(c, NULL);
    }
    fm3d_flush(c);
    fm2d_set_image_smoothing(a->c, a->smooth);
    fm2d_draw_image_scaled(a->c, g_sea_fb, 0, 0, (float)W, (float)H);
#else
    static int told;
    if (!told) printf("seascape scene: this build has no SPIR-V shaders (-Dspirv)\n");
    told = 1;
    fm2d_set_fill_color(a->c, FM_RGB(20, 20, 30));
    fm2d_fill_rect(a->c, 0, 0, W, H);
#endif
}

static fm_surface* make_crate(int n)
{
    fm_surface* s = fm_surface_create(n, n, FM_FORMAT_ARGB32);
    for (int y = 0; y < n; y++)
        for (int x = 0; x < n; x++) {
            int     edge = x < n / 10 || y < n / 10 || x >= n - n / 10 || y >= n - n / 10;
            int     diag = abs(x - y) < n / 14 || abs(x + y - n) < n / 14;
            int     hole = (x - n / 2) * (x - n / 2) + (y - n / 2) * (y - n / 2) < (n / 6) * (n / 6);
            uint8_t g    = (uint8_t)(120 + ((x * 7 + y * 13) & 31));
            fm_color c   = edge || diag ? FM_RGB(90, 60, 30) : FM_RGB(g + 60, g + 20, 40);
            if (hole) c = 0; /* transparent: shows the alpha test on billboards */
            fm_surface_row32(s, y)[x] = fm_premultiply(c);
        }
    return s;
}

/* The pipeline the shaders scene actually draws with (mirrors the fallbacks in scene_shaders). */
static const char* shader_pipeline_name(const app* a)
{
#if FM_FEATURE_SHADERS && FM_FEATURE_VBO
    if (a->shader_mode == SH_FIXED) return "fixed function T&L";
#  if FM_FEATURE_SPIRV
    int spv = SH_IS_SPIRV(a->shader_mode);
    if (spv && g_sh.init && !g_sh.spv_helmet) return "C shaders (SPIR-V failed)";
    if (a->shader_mode == SH_AOT) return "SPIR-V compiled to C";
    if (a->shader_mode == SH_JIT) return g_sh.spv_helmet && fm3d_spirv_jit_error(g_sh.spv_helmet) ? "SPIR-V JIT failed, interpreted" : "SPIR-V JIT (machine code)";
    if (spv) return "SPIR-V interpreted";
#  else
    if (a->shader_mode != SH_C) return "C shaders (no -Dspirv)";
#  endif
    return "C shaders";
#else
    (void)a;
    return "no programmable stages";
#endif
}

int main(int argc, char** argv)
{
    const char* shots = NULL;
    int         only  = 0;
    for (int i = 1; i + 1 < argc; i++) {
        if (!strcmp(argv[i], "--shots")) shots = argv[i + 1];
        if (!strcmp(argv[i], "--scene")) only = atoi(argv[i + 1]);
    }
    if (only < 0 || only > NSCENES) only = 0;
    if (!SDL_Init(SDL_INIT_VIDEO)) {
        SDL_Log("SDL_Init failed: %s", SDL_GetError());
        return 1;
    }
    SDL_Window*   win = NULL;
    SDL_Renderer* ren = NULL;
    if (!SDL_CreateWindowAndRenderer("fatmap sandbox", W, H, SDL_WINDOW_RESIZABLE, &win, &ren)) {
        SDL_Log("window/renderer failed: %s", SDL_GetError());
        return 1;
    }
    int vsync = 0;
    SDL_SetRenderVSync(ren, vsync);
    SDL_SetRenderLogicalPresentation(ren, W, H, SDL_LOGICAL_PRESENTATION_LETTERBOX);
    SDL_Texture* tex = SDL_CreateTexture(ren, SDL_PIXELFORMAT_ARGB8888, SDL_TEXTUREACCESS_STREAMING, W, H);
    SDL_SetTextureBlendMode(tex, SDL_BLENDMODE_NONE);

    app a;
    SDL_memset(&a, 0, sizeof(a));
    a.sc       = fm_swapchain_create(W, H, 2, 1);
    a.fb       = fm_swapchain_back(a.sc);
    a.c        = fm2d_create(a.fb);
    a.c3       = fm3d_create();
    a.filter3d = 2;
    a.persp3d  = 1;
    a.msaa3d   = 4;
    a.fox_clip = 1; /* Walk */
    {
        fm_surface* ft = make_texture(256, 256);
        fm_surface* ct = make_crate(128);
        a.floor_tex    = fm3d_texture_create(ft, 1);
        a.crate_tex    = fm3d_texture_create(ct, 1);
        fm_surface_destroy(ft);
        fm_surface_destroy(ct);
    }
    a.tex      = make_texture(256, 256);
    a.sprite   = make_sprite(64);
    for (int i = 0; i < FM_OP_COUNT; i++) a.tiles[i] = fm_surface_create(170, 165, FM_FORMAT_ARGB32);
    a.tile_ctx = fm2d_create(a.tiles[0]);
    a.exec     = fm_executor_create(0);
    a.threaded = 1;
    a.aa       = 1;
    a.smooth   = 1;
    a.count    = 2000;
    a.sea_div  = 4;

    printf("fatmap %s sandbox - SIMD best: %s (renderer: %s)\n", fm_version_string(), fm_simd_name(fm_simd_best()),
           SDL_GetRendererName(ren));
    printf("threads: %s, %d workers\n", fm_threads_supported() ? "yes" : "no", a.exec->workers);
    printf("keys: 1-9, 0, -, = scene, G shader/fixed, C fox clip, F filter, M perspective, N msaa, S simd, A antialias, B bilinear, T threads, Up/Down count, P profiler, V vsync, Space pause\n");
    printf("blend grid order:");
    for (int i = 0; i < FM_OP_COUNT; i++) printf(" %s", fm_blend_op_name((fm_blend_op)i));
    printf("\n");

    int      running = 1, paused = 0;
    int      shot_scene = 0, shot_frame = 0;
    double   shot_ms    = 0;
    if (shots) {
        a.scene    = only ? only - 1 : 0;
        shot_scene = a.scene;
        a.threaded = 0;
        printf("%-16s %12s %12s\n", "scene", "1 thread ms", "mt ms");
    }
    double shot_ms1 = 0;
    uint64_t last = fm_time_ns(), title_t = last;
    double   draw_acc = 0;
    int      frames = 0;
    while (running) {
        SDL_Event ev;
        while (SDL_PollEvent(&ev)) {
            SDL_ConvertEventToRenderCoordinates(ren, &ev);
            if (ev.type == SDL_EVENT_QUIT) running = 0;
            if (ev.type == SDL_EVENT_MOUSE_MOTION) {
                a.mx = ev.motion.x;
                a.my = ev.motion.y;
            }
            if (ev.type == SDL_EVENT_KEY_DOWN) {
                SDL_Keycode k = ev.key.key;
                if (k == SDLK_ESCAPE) running = 0;
                if (k >= SDLK_1 && k <= SDLK_9) a.scene = (int)(k - SDLK_1);
                if (k == SDLK_0) a.scene = 9;
                if (k == SDLK_MINUS) a.scene = 10;
                if (k == SDLK_EQUALS) a.scene = 11;
                if (k == SDLK_G) { /* the next pipeline this build has (seascape: SPIR-V only) */
                    do {
                        a.shader_mode = (a.shader_mode + 1) % SH_COUNT;
                    } while ((!FM_FEATURE_SPIRV && SH_IS_SPIRV(a.shader_mode)) ||
                             (!FM_SANDBOX_AOT && a.shader_mode == SH_AOT) ||
                             (FM_FEATURE_SPIRV && a.scene == 11 && !SH_IS_SPIRV(a.shader_mode)));
                    printf("shader pipeline: %s\n", shader_pipeline_name(&a));
                }
                if (k == SDLK_X) a.sea_fast = !a.sea_fast;
                if (k == SDLK_C) a.fox_clip++;
                if (k == SDLK_F) a.filter3d = (a.filter3d + 1) % 3;
                if (k == SDLK_M) a.persp3d = !a.persp3d;
                if (k == SDLK_N) a.msaa3d = a.msaa3d == 1 ? 4 : (a.msaa3d == 4 ? 8 : 1);
                if (k == SDLK_SPACE) paused = !paused;
                if (k == SDLK_A) a.aa = !a.aa;
                if (k == SDLK_B) a.smooth = !a.smooth;
                if (k == SDLK_T) a.threaded = !a.threaded;
                if (a.scene == 11) {
                    if (k == SDLK_UP && a.sea_div > 1) a.sea_div /= 2;
                    if (k == SDLK_DOWN && a.sea_div < 8) a.sea_div *= 2;
                } else {
                    if (k == SDLK_UP && a.count < 65536) a.count *= 2;
                    if (k == SDLK_DOWN && a.count > 1) a.count /= 2;
                }
                if (k == SDLK_V) {
                    vsync = !vsync;
                    SDL_SetRenderVSync(ren, vsync);
                }
                if (k == SDLK_S) {
                    fm_simd_level l = fm_simd_current();
                    do {
                        l = (fm_simd_level)((l + 1) % FM_SIMD_LEVELS);
                    } while (!fm_simd_supported(l));
                    fm_simd_set(l);
                }
                if (k == SDLK_P) {
                    char buf[8192];
                    fm_prof_report(buf, sizeof(buf));
                    printf("\n-- profiler (%s, %s) --\n%s", g_scene_names[a.scene], fm_simd_name(fm_simd_current()),
                           buf);
                    fflush(stdout);
                    fm_prof_reset();
                }
            }
        }
        uint64_t now = fm_time_ns();
        float    dt  = (float)((double)(now - last) / 1e9);
        last         = now;
        if (dt > 0.1f) dt = 0.1f;
        if (shots) dt = 1.0f / 60.0f; /* deterministic animation */
        if (!paused) a.t += dt;

        uint64_t d0 = fm_time_ns();
        a.fb = fm_swapchain_back(a.sc); /* always draw into the back buffer */
        fm2d_set_target(a.c, a.fb);
        fm2d_reset(a.c);
        fm2d_set_deferred(a.c, a.threaded);
        fm3d_set_deferred(a.c3, a.threaded);
        fm3d_set_msaa(a.c3, a.msaa3d);
        fm3d_set_executor(a.c3, a.threaded ? a.exec : NULL);
        fm2d_set_executor(a.c, a.threaded ? a.exec : NULL);
        fm2d_set_antialias(a.c, a.aa ? FM_AA_ANALYTIC : FM_AA_NONE);
        fm2d_set_antialias(a.tile_ctx, a.aa ? FM_AA_ANALYTIC : FM_AA_NONE);
        switch (a.scene) {
        case 0: scene_gallery(&a); break;
        case 1: scene_blend(&a); break;
        case 2: scene_stress(&a, paused ? 0.0f : dt); break;
        case 3: scene_texture(&a); break;
        case 4: scene_lines(&a); break;
        case 5: scene_compare(&a); break;
        case 6: scene_3d(&a); break;
        case 7: scene_troll(&a); break;
        case 8: scene_characters(&a); break;
        case 9: scene_helmet(&a); break;
        case 10: scene_shaders(&a); break;
        default: scene_seascape(&a); break;
        }
        fm2d_flush(a.c);
        fm3d_flush(a.c3);
        fm_prof_frame();
        double dms = (double)(fm_time_ns() - d0) / 1e6;
        draw_acc += dms;
        frames++;
        if (shots) {
            shot_ms += dms;
            if (++shot_frame == 60) {
                if (!a.threaded) {
                    /* same scene again, multithreaded */
                    shot_ms1   = shot_ms;
                    a.threaded = 1;
                    a.t        = 0;
                } else {
                    char path[512];
                    snprintf(path, sizeof(path), "%s/scene_%d.png", shots, shot_scene + 1);
                    fm_surface_write_png(a.fb, path);
                    printf("%-16s %12.3f %12.3f\n", g_scene_names[shot_scene], shot_ms1 / 60.0, shot_ms / 60.0);
                    a.threaded = 0;
                    if (++shot_scene == NSCENES || only) running = 0;
                    a.scene = shot_scene;
                    a.t     = 0;
                }
                shot_frame = 0;
                shot_ms    = 0;
            }
        }

        fm_surface* front = fm_swapchain_present(a.sc);
        SDL_UpdateTexture(tex, NULL, front->data, front->stride);
        SDL_RenderClear(ren);
        SDL_RenderTexture(ren, tex, NULL, NULL);
        SDL_RenderPresent(ren);

        if (now - title_t > 500000000ull) {
            char   title[256];
            char   scene[96];
            double secs = (double)(now - title_t) / 1e9;
            if (a.scene == 10)
                snprintf(scene, sizeof(scene), "%s: %s [G]", g_scene_names[a.scene], shader_pipeline_name(&a));
            else if (a.scene == 11)
                snprintf(scene, sizeof(scene), "%s: %s, %s math, %dx%d [G, X, Up/Down]", g_scene_names[a.scene],
                         FM_SANDBOX_AOT && a.shader_mode == SH_AOT
                             ? "SPIR-V compiled to C"
                             : (a.shader_mode == SH_JIT ? (g_sea && fm3d_spirv_jit_error(g_sea) ? "SPIR-V JIT failed, interpreted" : "SPIR-V JIT")
                                                        : "SPIR-V interpreted"),
                         a.sea_fast ? "fast" : "1 ulp", W / a.sea_div, H / a.sea_div);
            else
                snprintf(scene, sizeof(scene), "%s", g_scene_names[a.scene]);
            if (a.scene == 2)
                snprintf(title, sizeof(title), "fatmap | %s (%d) | %s | %s | %s | %.0f fps | draw %.2f ms",
                         scene, a.count, fm_simd_name(fm_simd_current()), a.aa ? "AA" : "aliased",
                         a.threaded ? "mt" : "1 thread", frames / secs, draw_acc / frames);
            else
                snprintf(title, sizeof(title), "fatmap | %s | %s | %s%s | %s | msaa %dx | %.0f fps | draw %.2f ms",
                         scene, fm_simd_name(fm_simd_current()), a.aa ? "AA" : "aliased",
                         a.smooth ? "" : " | nearest", a.threaded ? "mt" : "1 thread", a.msaa3d, frames / secs,
                         draw_acc / frames);
            SDL_SetWindowTitle(win, title);
            title_t  = now;
            frames   = 0;
            draw_acc = 0;
        }
    }

    fm2d_destroy(a.tile_ctx);
    fm2d_destroy(a.c);
    fm3d_destroy(a.c3);
    fm3d_texture_release(a.floor_tex);
    fm3d_texture_release(a.crate_tex);
    fm3d_texture_release(g_troll.tex_troll);
    fm3d_texture_release(g_troll.tex_pedestal);
    fm3d_texture_release(g_troll.tex_grass);
    obj_free(&g_troll.model);
    fm3d_texture_release(g_fox.tex);
    fm3d_texture_release(g_cesium.tex);
    gltf_free(&g_fox.m);
    gltf_free(&g_cesium.m);
    fm3d_texture_release(g_grass_fallback);
    fm3d_texture_release(g_helmet.tex);
    free(g_helmet.lit);
    gltf_free(&g_helmet.m);
#if FM_FEATURE_SHADERS && FM_FEATURE_VBO
    sh_free();
#endif
#if FM_FEATURE_SPIRV
    fm3d_spirv_destroy(g_sea);
    fm_surface_destroy(g_sea_fb);
#endif
    fm_swapchain_destroy(a.sc);
    for (int i = 0; i < FM_OP_COUNT; i++) fm_surface_destroy(a.tiles[i]);
    fm_executor_destroy(a.exec);
    fm_surface_destroy(a.tex);
    fm_surface_destroy(a.sprite);
    SDL_DestroyTexture(tex);
    SDL_DestroyRenderer(ren);
    SDL_DestroyWindow(win);
    SDL_Quit();
    return 0;
}
