#!/usr/bin/env python3
"""
Compile GLSL shaders to SPIR-V and embed them as C word arrays.

  python tools/compile_shaders.py <dir> <out.h> [--O0 name ...] [--also file ...]

Every *.vert / *.frag in <dir> (plus the files after --also) is compiled
with `glslc -O` (fatmap's SPIR-V backend needs functions inlined) into
    static const uint32_t spv_<name>_<stage>[] = { ... };
Names listed after --O0 are also compiled without optimization
(spv_<name>_<stage>_O0), e.g. to test that unsupported modules are rejected.
The generated header is committed, so building fatmap never needs glslc.
Needs glslc (Vulkan SDK / shaderc) on PATH.
"""
import os
import shutil
import subprocess
import sys
import tempfile


def compile_one(path, opt):
    fd, tmp = tempfile.mkstemp(suffix=".spv")
    os.close(fd)
    try:
        subprocess.check_call(["glslc", opt, path, "-o", tmp])
        data = open(tmp, "rb").read()
    finally:
        os.remove(tmp)
    return [int.from_bytes(data[i:i + 4], "little") for i in range(0, len(data), 4)]


def emit(out, name, words, src):
    out.append("/* %s */" % src)
    out.append("static const uint32_t %s[%d] = {" % (name, len(words)))
    for i in range(0, len(words), 8):
        out.append("    " + ", ".join("0x%08xu" % w for w in words[i:i + 8]) + ",")
    out.append("};")
    out.append("")


def main():
    if len(sys.argv) < 3:
        sys.exit(__doc__)
    if not shutil.which("glslc"):
        sys.exit("error: glslc not found (Vulkan SDK / shaderc)")
    src_dir, out_path = sys.argv[1], sys.argv[2]
    opts, cur = {"--O0": [], "--also": []}, None
    for a in sys.argv[3:]:
        if a in opts:
            cur = a
        elif cur:
            opts[cur].append(a)
        else:
            sys.exit(__doc__)
    o0 = opts["--O0"]
    guard = "FM_SPV_%s_H" % "".join(ch if ch.isalnum() else "_" for ch in os.path.normpath(src_dir)).upper()
    cmd = " ".join(["python", "tools/compile_shaders.py"] + [a.replace("\\", "/") for a in sys.argv[1:]])
    out = ["/* generated by tools/compile_shaders.py: do not edit; regenerate with", " *   %s */" % cmd,
           "#ifndef " + guard, "#define " + guard, "#include <stdint.h>", ""]
    files = [os.path.join(src_dir, f) for f in sorted(os.listdir(src_dir))] + opts["--also"]
    for path in files:
        f = os.path.basename(path)
        base, ext = os.path.splitext(f)
        if ext not in (".vert", ".frag"):
            continue
        stage = ext[1:]
        emit(out, "spv_%s_%s" % (base, stage), compile_one(path, "-O"), f + " (glslc -O)")
        if base in o0:
            emit(out, "spv_%s_%s_O0" % (base, stage), compile_one(path, "-O0"), f + " (glslc -O0)")
    out.append("#endif")
    with open(out_path, "w", newline="\n") as fh:
        fh.write("\n".join(out) + "\n")
    print("wrote", out_path)


if __name__ == "__main__":
    main()
