#!/usr/bin/env python3
"""
Compile GLSL shaders to SPIR-V and embed them as C word arrays.

  python tools/compile_shaders.py <dir> <out.h> [--O0 name ...]

Every *.vert / *.frag in <dir> is compiled with `glslc -O` (fatmap's SPIR-V
backend needs functions inlined) into
    static const uint32_t spv_<name>_<stage>[] = { ... };
Names listed after --O0 are also compiled without optimization
(spv_<name>_<stage>_O0), e.g. to test that unsupported modules are rejected.
The generated header is committed, so building fatmap never needs glslc.
Needs glslc (Vulkan SDK / shaderc) on PATH.
"""
import os
import shutil
import subprocess
import sys
import tempfile


def compile_one(path, opt):
    fd, tmp = tempfile.mkstemp(suffix=".spv")
    os.close(fd)
    try:
        subprocess.check_call(["glslc", opt, path, "-o", tmp])
        data = open(tmp, "rb").read()
    finally:
        os.remove(tmp)
    return [int.from_bytes(data[i:i + 4], "little") for i in range(0, len(data), 4)]


def emit(out, name, words, src):
    out.append("/* %s */" % src)
    out.append("static const uint32_t %s[%d] = {" % (name, len(words)))
    for i in range(0, len(words), 8):
        out.append("    " + ", ".join("0x%08xu" % w for w in words[i:i + 8]) + ",")
    out.append("};")
    out.append("")


def main():
    if len(sys.argv) < 3:
        sys.exit(__doc__)
    if not shutil.which("glslc"):
        sys.exit("error: glslc not found (Vulkan SDK / shaderc)")
    src_dir, out_path = sys.argv[1], sys.argv[2]
    o0 = sys.argv[sys.argv.index("--O0") + 1:] if "--O0" in sys.argv else []
    out = ["/* generated by tools/compile_shaders.py from %s: do not edit */" % src_dir.replace("\\", "/"),
           "#ifndef FM_SPV_%s" % os.path.basename(out_path).upper().replace(".", "_"),
           "#define FM_SPV_%s" % os.path.basename(out_path).upper().replace(".", "_"),
           "#include <stdint.h>", ""]
    for f in sorted(os.listdir(src_dir)):
        base, ext = os.path.splitext(f)
        if ext not in (".vert", ".frag"):
            continue
        path = os.path.join(src_dir, f)
        stage = ext[1:]
        emit(out, "spv_%s_%s" % (base, stage), compile_one(path, "-O"), f + " (glslc -O)")
        if base in o0:
            emit(out, "spv_%s_%s_O0" % (base, stage), compile_one(path, "-O0"), f + " (glslc -O0)")
    out.append("#endif")
    with open(out_path, "w", newline="\n") as fh:
        fh.write("\n".join(out) + "\n")
    print("wrote", out_path)


if __name__ == "__main__":
    main()
